### ISSUE TITLE
Vision Image Detector API is not detecting color properly

### ISSUE THREAD

**Issue by umashankar-pardhi-amla** [googleapis/nodejs-vision#1009]
Hi I have tried a couple of scenarios with the different images the color is not getting properly 

Here are  images I have used 

![1](https://user-images.githubusercontent.com/79130351/166231344-192b4932-181f-459b-b1a8-979e4c437101.png)

![google2 0 0](https://user-images.githubusercontent.com/79130351/166231272-5f42c30c-53ac-4719-8b33-f4c71518745b.jpg)

**Comment by aribray** [comment]
I transferred this issue to the `nodejs-vision` client library repository
