### ISSUE TITLE
Cloud Vision accepting external url

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-vision#101]
_From @lovelovelovelovelovelovelove on June 23, 2018 17:57_

I saw your API that allows for  Cloud Vision API to analise external links. I tried to follow the links to find out more on your API and how it could help me but seemed depreciated. Is your API still working and where can I find its documentation?
Node js

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#2833_

**Comment by stephenplusplus** [comment]
Sorry for the confusion-- we're not deprecated :) [Here are the docs](https://cloud.google.com/nodejs/docs/reference/vision/0.19.x)!
