### ISSUE TITLE
batch-annotate-files returns different than async-batch-annotate-files

### ISSUE THREAD

**Issue by schmidtGabriel** [googleapis/nodejs-vision#1017]
Hello. I'm using the batchAnnotateFiles function for a time and currently start to return the text wrong. So i changed to asyncbatchAnnotateFiles function and it return the text as the way i need. But the async function save the json on cloud and i need this text inside the code like as in not async function. Anyone know a solution for this? Answer me back if yes. Thank you.

#### Environment details

  - OS: MacOs Monterey
  - Node.js version: v14.17.6
  - npm version: 6.14.15
  - `@google-cloud/vision` version: ^2.0.0

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by ivanmkc** [comment]
Hi, can you elaborate with:
1) A code sample
2) Expected result
3) Actual result

Thanks!
