### ISSUE TITLE
Updates to library surfaced failing tests

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-vision#1025]
Prior to the updates in https://github.com/googleapis/nodejs-vision/pull/1016, only the `product sets` suite of tests was running in integration.

When all tests were enabled, many flaky/failing tests have been surfaced.

---

_Note: when fixing tests we should also ensure that resources created during test runs are cleaned, I believe vision has likely been leaking resources for quite some time._

**Comment by meredithslota** [comment]
Closing as samples have moved to https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/main/vision (and will be removed from this repo shortly, but testing is already happening in the new location). If there are failing tests related to the library builds, let's resurface, but most of the failing tests were sample related.
