### ISSUE TITLE
Please bump google-gax to 3.1.4

### ISSUE THREAD

**Issue by alamothe** [googleapis/nodejs-vision#1035]
Please bump `google-gax` to 3.1.4 and release a new version.

**Comment by meredithslota** [comment]
We are currently requiring google-gax ^3.5.2: https://github.com/googleapis/nodejs-vision/blob/main/package.json#L49 — although that change hasn't been released yet. The latest released version requires ^3.3.0 and that was released in v3.0.1 in September 2022.
