### ISSUE TITLE
annotations.proto` was not found

### ISSUE THREAD

**Issue by HiroshiHorie** [googleapis/nodejs-vision#114]
Hello,
require('@google-cloud/vision')

causes the following error:
Error: The include `google/api/annotations.proto` was not found.

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share a few things with us?
- what version of nodejs are you using?
- what version of @google-cloud/vision are you using?

**Comment by HiroshiHorie** [comment]
Hello thanks for your reply,

- node -v = v10.6.0
- "@google-cloud/vision": "0.20.0"

**Comment by JustinBeckwith** [comment]
Greetings!  As best I can tell, this appears to be working.  There are however a few things you can try:
- Upgrade to the latest version of node.js 10
- Delete your `node_modules` folder and `package-lock.json`, then run `npm install` again
- Run `npm cache clean --force` and `npm install` again

If you're still running into problems... please do let me know!
