### ISSUE TITLE
Drop dependency on nodejs-common

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-vision#115]
This module pulls in `@google-cloud/common`, which is a fairly meaty module.  It's only using it for the implementation of promisify:
https://github.com/googleapis/nodejs-common/blob/master/src/util.ts#L934

I'm thinking about creating a new npm module with just the `promisify` functions we use in common.  `pify` doesn't work exactly the same way, in that it's `multiArgs` flag causes it to return the results as an array, but ALSO causes the errors to come back as an array 🤦‍♀️

Any thoughts?  @stephenplusplus @ofrobots @googleapis/node-team

**Comment by stephenplusplus** [comment]
This has evolved into a PR: https://github.com/googleapis/nodejs-common/pull/189. We can talk it out over there :)
