### ISSUE TITLE
TypeError: client.setCredentials is not a function

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-vision#15]
_From @Samartan on November 29, 2017 11:7_

Hello everyone! I have been trying to follow the Cloud vision with Node.js codelab. I am able to start the google sign in flow but after I have selected an account to sign in. I get TypeError as explained below.

Sorry for changing the title that many times. I got a bit sloppy there. 

Please run down the following list and make sure you've tried the usual "quick fixes":

  [done] Search the issues already opened: https://github.com/GoogleCloudPlatform/google-cloud-node/issues
  [done] Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
  [done] Check our Troubleshooting guide: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/troubleshooting
  [done]  Check our FAQ: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/faq

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: MacOs
  - Node.js version:v8.9.1
  - npm version:5.5.1
  - google-cloud-node version: v6.11.1

#### Steps to reproduce
Follow steps from the codelab.

Error shown:
```
home/user/cloud-vision/start/lib/oauth2.js:172
      client.setCredentials(tokens);
             ^
TypeError: client.setCredentials is not a function
    at /home/user/cloud-vision/start/lib/oauth2.js:172:14
    at /home/user/cloud-vision/start/node_modules/google-auth-library/lib/auth/oauth2client.js:95:13
    at Request._callback (/home/user/cloud-vision/start/node_modules/google-auth-library/lib/transporters.js:113:17)
    at Request.self.callback (/home/user/cloud-vision/start/node_modules/google-auth-library/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/user/cloud-vision/start/node_modules/google-auth-library/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/user/cloud-vision/start/node_modules/google-auth-library/node_modules/request/request.js:1085:12)
```

Further Information: 

The credentials set up is proper because I put in the details into the "Complete" version of the Codelab and I could sigin perfectly. So I thought there must be something wrong with the coding part but I have checked it twice and everything is the same as in the codelab. 

Thanks!

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#2758_

**Comment by stephenplusplus** [comment]
I'm very sorry for the delay on this issue. Would you mind linking to where you are finding the codelab as well as any reproduction steps that could help me see the code you are running? Thanks!

**Comment by stephenplusplus** [comment]
Due to the age of the issue, I'm going to close it as I'm unable to help without more information. If there is still an issue we need to fix, please let me know-- we definitely don't want any misleading docs out there. Thank you, and sorry for the trouble.

**Comment by richardson-trevor** [comment]
@stephenplusplus I just came across this issue as well. When I try to recreate the example code from [this cloud func example](https://cloud.google.com/solutions/authentication-in-http-cloud-functions) I get 'setCredentials is not a function'.

**Comment by richardson-trevor** [comment]
NM, just found that a solution to this issue is being worked on [here](https://github.com/google/google-auth-library-nodejs/issues/189).
