### ISSUE TITLE
v0.14.0 hasn't been published to NPM

### ISSUE THREAD

**Issue by nicolasgarnier** [googleapis/nodejs-vision#16]
All in the title. On NPM the published version is 0.13: 
![image](https://user-images.githubusercontent.com/3766663/34227951-4b8bb9a8-e5cf-11e7-82d5-59f88546b7aa.png)

**Comment by stephenplusplus** [comment]
Thanks for the heads up. I'll get that fixed.

**Comment by stephenplusplus** [comment]
0.14.0 is now live 👍 

(...really)
