### ISSUE TITLE
Can't seem to access Vision.types that we had in 0.12

### ISSUE THREAD

**Issue by nicolasgarnier** [googleapis/nodejs-vision#17]
This is a followup from https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2516

I had this issue where we could not compare Likelyhoods and this was fixed using Types.

However in 0.13.0 I can't seem to find the types anymore. I used to be able to do:

```js
var Vision = require('@google-cloud/vision')
var visionClient = new Vision({...})

visionClient.annotateImage({...})
  .then(responses => {
    var response = responses[0]
    console.log(Vision.types.Likelihood[response.safeSearchAnnotation.adult]) // 1
  })
```

Are the types published in a different node modules?

**Comment by nicolasgarnier** [comment]
Look like this is gone. https://github.com/googleapis/nodejs-vision/blob/v0.12.0/src/index.js#L78

Would it be possible to add the grpc generated Types back?

**Comment by stephenplusplus** [comment]
Confirmed; these were definitely lost when we transitioned to an auto-generated bottom layer. I'll ask around to see if we lost these for a reason, or if we can find a way to get them back.

For now, here is a much less intuitive way to do this:

```js
const vision = require('@google-cloud/vision')
const path = require('path')
const grpc = require('google-gax').grpc()

const likelihood = grpc.loadProto(
  path.join(require.resolve('@google-cloud/vision'), '..', '..', 'protos'),
  `google/cloud/vision/v1/image_annotator.proto`
).google.cloud.vision.v1.Likelihood.values;

likelihood == {
  UNKNOWN: 0,
  VERY_UNLIKELY: 1,
  UNLIKELY: 2,
  POSSIBLE: 3,
  LIKELY: 4,
  VERY_LIKELY: 5
}
```

**Comment by nicolasgarnier** [comment]
Cool thx!

Since this for a [Firebase Codelab](https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/index.html?index=..%2F..%2Ffirebase17#8) I'll revert to using 0.12.0 for now since codelabs code should look elegant and simple :D

Please let me know if/when Types makes it back in :)

**Comment by stephenplusplus** [comment]
Opened an issue to talk it over: https://github.com/googleapis/toolkit/issues/1756

**Comment by stephenplusplus** [comment]
Looks like https://github.com/googleapis/gapic-generator/issues/1756 was closed, which effectively closes this. Goodbye, #17.
