### ISSUE TITLE
safeSearchDetection not finding image

### ISSUE THREAD

**Issue by 00hello** [googleapis/nodejs-vision#18]
I've been stuck on this problem for the past 36 hours. I'm going through the Codelabs tutorial for [Firebase Cloud Functions](https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#8)

My app is already deployed to firebase hosting, I'm using version 0.14.0 of nodejs-vsion.  However, when doing the image moderation part and after deploying, first I got this error

> TypeError: Vision is not a constructor

referring to my require and constructor statements
```js
const Vision = require('@google-cloud/vision');
const vision = new Vision();
```
Which are copied exactly from the tutorial.

I saw in the [documentation](https://cloud.google.com/vision/docs/detecting-safe-search#running_safe_search_detection_on_a_remote_image), that I should use 

```js
const vision = require('@google-cloud/vision');
const client = new vision.ImageAnnotatorClient();
```

So I changed my code to 

```js
const Vision = require('@google-cloud/vision');
const vision = new Vision.ImageAnnotatorClient();
```

It deploys but now when I upload an image, it displays on the app but it doesn't get blurred as it's supposed to. Instead, I get an error in the function logs saying

> Error: No image present.
>     at _coerceRequest (/user_code/node_modules/@google-cloud/vision/src/helpers.js:68:21)
>     at ImageAnnotatorClient.<anonymous> (/user_code/node_modules/@google-cloud/vision/src/helpers.js:223:12)
>     at ImageAnnotatorClient.wrapper [as annotateImage] (/user_code/node_modules/@google-cloud/vision/node_modules/@google-cloud/common/src/util.js:746:29)
>     at ImageAnnotatorClient.<anonymous> (/user_code/node_modules/@google-cloud/vision/src/helpers.js:140:17)
>     at /user_code/node_modules/@google-cloud/vision/node_modules/@google-cloud/common/src/util.js:777:22
>     at ImageAnnotatorClient.wrapper [as safeSearchDetection] (/user_code/node_modules/@google-cloud/vision/node_modules/@google-cloud/common/src/util.js:761:12)
>     at exports.blurOffensiveImages.functions.storage.object.onChange.event (/user_code/index.js:75:17)
>     at correctMediaLink (/user_code/node_modules/firebase-functions/lib/providers/storage.js:78:20)
>     at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:35:20
>     at process._tickDomainCallback (internal/process/next_tick.js:135:7)
> 

Here is the relevant code straight from the tutorial, 

```js
const image = {
    source: {imageUri: `gs://${object.bucket}/${object.name}`}
};

return vision.safeSearchDetection(image)
    .then(batchAnnotateImagesResponse => {
```

So I switched to the code that is in the [docs](https://cloud.google.com/vision/docs/detecting-safe-search#running_safe_search_detection_on_a_remote_image), instead of using the 'image' object, I just put the image url directly inside the safeSearchDetection function

```js
return vision.safeSearchDetection(`gs://${object.bucket}/${object.bucket}`)
```

~~(The back-ticks around the argument won't display correctly because they are how markdown displays code format)~~ (edited by @stephenplusplus)

 
And now the error in the Function logs is
```
blurOffensiveImages 
  [ 
    { 
        faceAnnotations: [],
        landmarkAnnotations: [],
        logoAnnotations: [],
        labelAnnotations: [],
        textAnnotations: [],
        safeSearchAnnotation: null,     
        imagePropertiesAnnotation: null,    
        error:   {   
                details: [],        
                code: 7,        
                message: 'Error opening file: gs://friendlychat-XXXX.appspot.com/XXXXXXX/-XXXXXXXXX/XXXXXXX.jpg.' },
        cropHintsAnnotation: null,     
        fullTextAnnotation: null,     
        webDetection: null 
   } 
]
```

My object.bucket is the 'friendlychat-XXXX.appspot.com' part and my object.name is the 'XXXXXXX/-XXXXXXXXX/XXXXXXX.jpg' part

I don't know what else to do. I've tried reverting back to version 0.12.0 and 0.11.0 and nothing helps. Those just give me different errors requiring me to change the `vision = new Vision...` constructor. And even after making adjustments, the image still isn't able to be found.

Again, the image uploads, but the function to blur isn't running because it can't find the image. I'm really stuck here.

**Comment by stephenplusplus** [comment]
First of all, thanks for putting up with the version changes and the out of date docs. I'll work separately to see who owns them and correct the examples so nobody else has to endure what you have.

It seems to me like you've found the correct way to use our code. The error that you ended up with:

> 'Error opening file: gs://friendlychat-XXXX.appspot.com/XXXXXXX/-XXXXXXXXX/XXXXXXX.jpg.'

That is directly from the API, un-touched by our client library. So, for some reason, the API cannot find your image by specifying it as a `gs://` path. I would try downloading the image locally and pushing it right up in the request:

```js
const bucket = gcs.bucket(object.bucket);
const file = bucket.file(object.name);

file.download()
  .then(resp => {
    var imageContents = resp[0];
    return vision.safeSearchDetection(imageContents);
  })
  .catch(err => {
    console.log('Image downloading failed.', err):
  });
```

Hope that works 🤞 Sorry again for all of the inconsistencies and changes.

**Comment by 00hello** [comment]
That got me further along. Thanks.

But I had to make a few modifications in order to get it completely working though.  I'll outline them here for posterity -until the docs and tutorial are updated. 

Once I switched to the download method, I got this error

> ApiError: friendlychat-XXXXX@appspot.gserviceaccount.com does not have storage.objects.get access to friendlychat-XXXXX.appspot.com/XXXXXXXXXX/XXXXXXXXXX/XXXXXXXXXX.jpg.     at Object.parseHttpRespMessage (/user_code/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/src/util.js:161:33)     at Object.handleResp (/user_code/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/src/util.js:136:18)     at Duplexify.self.requestStream.on.on.res (/user_code/node_modules/@google-cloud/storage/src/file.js:542:21)     at emitOne (events.js:96:13)     at Duplexify.emit (events.js:188:7)     at emitOne (events.js:96:13)     at DestroyableTransform.emit (events.js:188:7)     at onResponse (/user_code/node_modules/@google-cloud/storage/node_modules/retry-request/index.js:189:19)     at Request.<anonymous> (/user_code/node_modules/@google-cloud/storage/node_modules/retry-request/index.js:144:11)     at emitOne (events.js:96:13)

Which I gather, means the user profile used to run the hosted firebase app does not have read/write permission on objects in storage. 

So you'll need to go into the console -> [https://console.cloud.google.com/iam-admin/iam/project?project](https://console.cloud.google.com/iam-admin/iam/project?project)=friendlychat-XXXXX

(replace "friendlychat-XXXXX" with whatever you project's id is)

Select the App Engine default service account's role drop down menu and add "Storage Object Creator" and "Storage Object Viewer" permissions. Granted, you may only need  "... Viewer" to download but since you're going to be uploading it again, I assumed I should add "... Creator", as well.

And until the Vision.types get restored, in order to use the Vision.types.Likelihood, you'll need to implement [this workaround](https://github.com/googleapis/nodejs-vision/issues/17#issuecomment-353183850)


And it should work now. 

Also, do not use vision.detectSafeSearch, as can be seen in several places (like [this doc](https://cloud.google.com/functions/docs/tutorials/imagemagick) ). As I believe it's been deprecated.

**Comment by 00hello** [comment]
Ok. I figured it out. I had a suspicion that the original error that I was getting that started this entire issue might have been caused by the read/write permission on objects in storage. So now that I had set those permissions, I switched back to 

```js
return vision.safeSearchDetection(`gs://${object.bucket}/${object.bucket}`)
```
And it worked!

You still can't use the 'image' object that the tutorial gives you as the argument. 
```
const image = {
    source: {imageUri: `gs://${object.bucket}/${object.name}`}
};
```
So just ignore it.


The fact that the original error I got was just 

> Error: No image present.
> at _coerceRequest (/user_code/node_modules//src/helpers.js:68:21)
> ....

...was not very helpful. It should have told me that my permissions were wrong. It was only until I switched to downloading the image first that I was told the problem was with my permissions.

**Comment by stephenplusplus** [comment]
I think the blame for all of this goes to the tutorial using an outdated version of our code. We need to go back and update that, which would have prevented most of this, up until the "Error opening file: gs://..." error.

The error "No image present." is from our code-- we changed the way images are sent to us since the version that's used in the tutorial.

The error "Error opening file: gs://friendlychat-XXXX.appspot.com/XXXXXXX/-XXXXXXXXX/XXXXXXX.jpg." is the one that meant permissions were incorrect, and that one came from the API.

I'm going to close this issue, since we can't correct anything from here.

@alexander-fenster @jmdobry, do you know how we should go having [this tutorial](https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#8) updated to reflect the changes we've made to Vision?

**Comment by stephenplusplus** [comment]
@alexander-fenster @jmdobry you can ignore that question. I forgot they are blocked from updating their example by https://github.com/googleapis/toolkit/issues/1756.

**Comment by tcha-tcho** [comment]
I Lose a entire day looking for this. Probably this info about the permissions should be at the documentations of vision as well. It's too critical.

**Comment by shekharskamble** [comment]
@00hello Thank you for your investigation I am having the exact same problem and unable to find the  "Storage Object Creator" & "Storage Object Viewer" permissions in the link given by you also is it possible for you to post your working code?

**Comment by 00hello** [comment]
@shekharskamble  You're welcome.  

### "Storage Object Creator" & "Storage Object Viewer" permissions
With regards to "Storage Object Creator" & "Storage Object Viewer" permissions, after following the link I posted above (now below) --

> https://console.cloud.google.com/iam-admin/iam/project?project= friendlychat-XXXXX
> (replace "friendlychat-XXXXX" with whatever your project's id is)

-- I trust, you'll see something that looks like this. 

![screenshot](https://user-images.githubusercontent.com/445986/35515312-d66f5112-04d6-11e8-8948-5ad7647783c1.png)

There should be an "App Engine default service account" listed (second from the top in the screenshot). Click the little dropdown button to the right. See where mine says "multiple" (Yours probably won't say "multiple" because it might only have one permission selected). Scroll down the list till you get to "Storage" near the bottom.  Drag your mouse over the blue arrow to the right of "Storage" and the "Storage ..." permission menu should make itself visible as you can see in the screenshot. 

### Code
And here's the code.  The parts that I commented out still remain to show you what wasn't needed.  Also, I kept the console logs that I was using to debug. Let me know if this works for you.

```
exports.blurOffensiveImages = functions.storage.object().onChange(event => {
    const object = event.data;
    //const file = gcs.bucket(object.bucket).file(object.name);
    
    // Exit if this is a deletion or a deploy event.
    if (object.resourceState === 'not_exists') {
    return console.log('This is a deletion event.');
    } else if (!object.name) {
    return console.log('This is a deploy event.');
    }

    // const image = {
    //    source: {imageUri: `gs://${object.bucket}/${object.name}`}
    // };
    
    // var visionPromise = file.download()
    //     .then(resp => {
    //         var imageContents = resp[0];
    //         return vision.safeSearchDetection(`gs://${object.bucket}/${object.name}`);
    //     })
  
  
    // Check the image content using the Cloud Vision API.
    return vision.safeSearchDetection(`gs://${object.bucket}/${object.name}`).then(batchAnnotateImagesResponse => {
            console.log("batchAnnotateImagesResponse");
            console.log(batchAnnotateImagesResponse);
            console.log("batchAnnotateImagesResponse[0]");
            console.log(batchAnnotateImagesResponse[0]);
            const safeSearchResult = batchAnnotateImagesResponse[0].safeSearchAnnotation;
            console.log("safeSearchResult.adult");
            console.log(safeSearchResult.adult);
            //const Likelihood = Vision.types.Likelihood;
            if (Likelihood[safeSearchResult.adult] >= Likelihood.LIKELY ||
                Likelihood[safeSearchResult.violence] >= Likelihood.LIKELY) {
                console.log('The image', object.name, 'has been detected as inappropriate.');
                return blurImage(object.name, object.bucket);
            } else {
                console.log('The image', object.name,'has been detected as OK.');
            }
        })
        .catch(err => {
            console.log('Search Detecion failed.', err);
        });
});

```

**Comment by shekharskamble** [comment]
Thank you so so much @00hello, its working.....

**Comment by ColDrekken** [comment]
Hello @00hello, I run into the same error.  I also follow your hint on permissions but it still throws the same error Message : Error: No image present.

- Project is right one.
- gs path is correct: eg. gs:/XXXXXXXXXXX.appspot.com/avatars/mRVETL68lfhHDpoHKm6tTB567pD2
- permissions are set to Storage Object Viewer and Creator.

One point i'm unsure. When uploading the picture to storage the file is saved without .png or .jpeg . Could this cause trouble too?

Best regards

**Comment by 00hello** [comment]
@ColDrekken  Yes, all image files, if they're to be recognized as images by the computer, must have some sort of image like extension (e.g. .png, .jpg, .jpeg etc). Look at the extension the image has before it's uploaded to storage and make sure you're saving it with the same extension

**Comment by cpmech** [comment]
regardless, I still get the `No image present. at _coerceRequest` error.

So, I'm wondering if there is an updated tutorial on how to use the 0.19.0 version?

**Comment by JustinBeckwith** [comment]
Looping in @fhinkel!

**Comment by cpmech** [comment]
:-) I've managed to get something working using the following package.json

```
{
  "name": "myproj",
  "version": "0.0.1",
  "private": true,
  "license": "Apache-2.0",
  "author": "me",
  "engines": {
    "node": ">=6.11.5"
  },
  "scripts": {
    "test": "echo 'no tests yet'"
  },
  "dependencies": {
    "@google-cloud/storage": "^1.7.0",
    "@google-cloud/vision": "^0.19.0"
  },
  "devDependencies": {
    "@google-cloud/nodejs-repo-tools": "^2.3.0"
  },
  "cloud-repo-tools": {
    "requiresKeyFile": true,
    "requiresProjectId": true
  }
}
```

and the following code
```
'use strict';

const config = require('./config.json');
const storage = require('@google-cloud/storage')();
const vision = require('@google-cloud/vision');

function detectText(bucketName, fileName) {
  const client = new vision.ImageAnnotatorClient();
  const path = `gs://${bucketName}/${fileName}`;
  console.log(`performing OCR on ${path}`);
  return client.documentTextDetection(path)
    .then(results => {
      const pages = results[0].fullTextAnnotation.pages;
      let output = [];
      pages.forEach(page => {
        let data = {
          blocks: []
        };
        page.blocks.forEach(block => {
          let blk = {
            conf: block.confidence,
            bounds: block.boundingBox.vertices,
            paras: [],
          };
          block.paragraphs.forEach(paragraph => {
            let para = {
              conf: paragraph.confidence,
              bounds: paragraph.boundingBox.vertices,
              words: [],
            };
            paragraph.words.forEach(word => {
              para.words.push({
                conf: word.confidence,
                text: word.symbols.map(s => s.text).join('')
              });
            });
            blk.paras.push(para);
          });
          data.blocks.push(blk);
        });
        output.push(data);
      });
      const jsonstr = JSON.stringify(output);
      const outFilename = `${fileName}.json`;
      const outBucketName = config.RESULT_BUCKET;
      const file = storage.bucket(outBucketName).file(outFilename);
      console.log(`saving result to ${outFilename} in bucket ${outBucketName}`);
      return file.save(jsonstr);
    })
    .catch(err => {
      console.error('ERROR:', err);
    });
}

exports.processImage = (event) => {
  let file = event.data;
  return Promise.resolve()
    .then(() => {
      if (file.resourceState === 'not_exists') { // deletion event => skip
        return;
      }
      if (!file.bucket) {
        throw new Error('bucket property missing in request');
      }
      if (!file.name) {
        throw new Error('name property missing in request');
      }
      return detectText(file.bucket, file.name);
    })
    .then(() => {
      console.log(`file ${file.name} processed.`);
    });
};
```

I'm not sure if my fiddling with permissions affected the results or not... :-/

We definitively need a less confusing tutorial...

**Comment by fhinkel** [comment]
Thanks for raising the issue. I'll work on it.

**Comment by fhinkel** [comment]
cc @samtstern

**Comment by fhinkel** [comment]
cc @nicolasgarnier

**Comment by nicolasgarnier** [comment]
FYI the tutorial specifies to install v0.12 of the Vision SDK. As described in [Step 9](https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#8)

```
npm install --save @google-cloud/vision@0.12.0 @google-cloud/storage@1.5.1 child-process-promise@2.2.1
```

That's because - last time I checked - there was no elegant and simple way to compare the level of likelyhood of a safesearch. I reported this here: https://github.com/googleapis/nodejs-vision/issues/17

That being said, installing v0.12 should have the code in the tutorial working. About the permission issue I'm not sure why your script does not have permission to access the image since you're running in a trusted environment and the application default credentials normally have access to the bucket by default in Cloud Functions.
My guess is that there was an issue when the Firebase project was initialized and some permissions didn't get set correctly. Creating and using a new project is likely to fix this. Normally the code in the tutorial simply runs as-is without having to touch the permissions manually, although, I'll double check and re-deploy on a new project to make sure of that.

(also FYI there is a "finished" version of the codelab in https://github.com/firebase/friendlychat-web/tree/master/cloud-functions that you can use directly)

**Comment by cpmech** [comment]
Thanks! It's working now.
