### ISSUE TITLE
TypeError: Cannot read property 'ImageAnnotatorClient' of undefined

### ISSUE THREAD

**Issue by sandrapavankumar** [googleapis/nodejs-vision#191]
I'm new to nodejs, trying google handwriting text recognition. The error log and code is given below, please suggest me.

```js
function test(){
    const vision = require('@google-cloud/vision').v1p3beta1;
    const fs = require('fs');
    const client = new vision.ImageAnnotatorClient();
    const fileName = `C:/Users/sandr/Downloads/menu.jpg`;

    const request = {
    image: {
        content: fs.readFileSync(fileName),
    },
    feature: {
        languageHints: ['en-t-i0-handwrit'],
    },
    };
    client
    .documentTextDetection(request)
    .then(results => {
        const fullTextAnnotation = results[0].fullTextAnnotation;
        console.log(`Full text: ${fullTextAnnotation.text}`);
    })
    .catch(err => {
        console.error('ERROR:', err);
    });  
}

console.log(test());
```

```
    const client = new vision.ImageAnnotatorClient();
                              ^

TypeError: Cannot read property 'ImageAnnotatorClient' of undefined
    at test (D:\Softwares\nodejs-docs-samples-master\nodejs-docs-samples-master\functions\ocr\app\MyApp.js:8:31)
    at Object.<anonymous> (D:\Softwares\nodejs-docs-samples-master\nodejs-docs-samples-master\functions\ocr\app\MyApp.js:34:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
```

#### Environment details

  - OS: Windows 10
  - Node.js version: 10.10.0
  - npm version: 6.4.1
  - `@google-cloud/vision` version: 0.19.0

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  I could be wrong, but I don't think you shouldn't need the `.v1p3beta1`.  Will this work without it?

**Comment by sandrapavankumar** [comment]
When I remove .v1p3beta1. and try I get an error "TypeError: vision.ImageAnnotatorClient is not a constructor"

**Comment by sandrapavankumar** [comment]
Hi @JustinBeckwith, can you please suggest if this is a bug in vision api.

**Comment by stephenplusplus** [comment]
I believe you just need to upgrade to the latest version of this library, which is currently `0.22.0`.

With that version, this works for me:

```js
const vision = require('@google-cloud/vision')
const client = new vision.ImageAnnotatorClient()
```

Please let me know if you still have issues after the upgrade.

**Comment by sandrapavankumar** [comment]
I just tried with the latest version, and facing new errors. Kindly suggest me if anything wrong in code.
(node:8904) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
(node:8904) UnhandledPromiseRejectionWarning: Error: Unexpected error while acquiring application default credentials: Could not load
the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
    at GoogleAuth.<anonymous> (C:\Users\sandrpa\Downloads\nodejs-docs-samples-master\functions\ocr\app\node_modules\@google-cloud\vision\node_modules\google-auth-library\build\src\auth\googleauth.js:248:31)

**Comment by stephenplusplus** [comment]
https://cloud.google.com/docs/authentication/getting-started#auth-cloud-implicit-nodejs has some good information about getting started with authorization.

**Comment by sandrapavankumar** [comment]
Thanks @stephenplusplus its working now.
