### ISSUE TITLE
PDF/TIFF Document Text Detection on local files.

### ISSUE THREAD

**Issue by sandrapavankumar** [googleapis/nodejs-vision#195]
Greetings, 
Please consider this as a question/doubt !!
Documentation about text detection from PDF and TIFF files stored in Google Cloud Storage is clearly explained. Can we also detect the text from local PDF files ? If so can you please update the documentation.
 I tried but couldn't be able to detect the text from the locally saved PDF files. 

Thanks!
Pavan.

**Comment by stephenplusplus** [comment]
Judging from the text on [this page](https://cloud.google.com/vision/docs/pdf), it doesn't seem possible, unfortunately:

> The Vision API can detect and transcribe text from PDF and TIFF files stored in Google Cloud Storage.

**Comment by mohit67890** [comment]
PDF/TIFF Document Text Detection
How Can I create the Searchable Text PDF from the JSON response of PDF/TIFF Document Text Detection.
Also, How can I convert the BoundingBox Vertices into Top, Left, Width, Height.

Response from JSON is below:

"boundingBox":{"normalizedVertices":[{"x":0.14478114,"y":0.046428572},{"x":0.2777778,"y":0.046428572},{"x":0.2777778,"y":0.06666667},{"x":0.14478114,"y":0.06666667}]},"symbols":[{"property":{"detectedLanguages":[{"languageCode":"en"}]},"text":"R","confidence":0.99},{"property":{"detectedLanguages":[{"languageCode":"en"}]},"text":"e","confidence":1},{"property":{"detectedLanguages":[{"languageCode":"en"}]},"text":"l","confidence":0.99},{"property":{"detectedLanguages":[{"languageCode":"en"}]},"text":"i","confidence":0.99},{"property":{"detectedLanguages":[{"languageCode":"en"}]},"text":"a","confidence":0.99},{"property":{"detectedLanguages":[{"languageCode":"en"}]},"text":"n","confidence":1},{"property":{"detectedLanguages":[{"languageCode":"en"}]},"text":"c","confidence":1},{"property":{"detectedLanguages":[{"languageCode":"en"}],"detectedBreak":{"type":"EOL_SURE_SPACE"}},"text":"e","confidence":1}],"confidence":0.99}
