### ISSUE TITLE
vision.ImageAnnotatorClient is not a constructor?

### ISSUE THREAD

**Issue by squarenotch** [googleapis/nodejs-vision#20]
I am new to node.js and have struggled with the above error message for over 6 hours. Ive tried every example I can find on the web but always end up with an errr when trying to create a client object. Stripped down code as follows always results in the error in the title. Any help would be greatly appreciated. Thank you.

```javascript
'use strict';

const path = require('path');
const gcs = require('@google-cloud/storage')();
const vision = require('@google-cloud/vision')();

exports.tagImage = (event) => {
  const object = event.data;

  
  const client = new vision.ImageAnnotatorClient();

};

```

**Comment by squarenotch** [comment]
Got it working but wow are the docs out of date! The package.json file needs to have "@google-cloud/vision": "0.14.0", and the index.js file should read const client = new vision.v1.ImageAnnotatorClient({});

There are many, many differing documents online about this library but none of them said to use the above.

**Comment by stephenplusplus** [comment]
Sorry for the trouble. Which docs were you reading?

**Comment by squarenotch** [comment]
No problem, over the moon to get past it! There are quite a few pages i've stumbled across but this one in particular seems to be the one I would think would be up to date. 

https://cloud.google.com/vision/docs/reference/libraries

**Comment by stephenplusplus** [comment]
The example from that document actually works from me, although I think it could be more clear and show the exact version it is using. (@jmdobry @alexander-fenster is there a place to file a feature request for the docs site?)

I did run into a problem when I tried the snippet from your post:

```js
const vision = require('@google-cloud/vision')();
const client = new vision.ImageAnnotatorClient();
```

To get it working, I had to:

```diff
- const vision = require('@google-cloud/vision')();
+ const vision = require('@google-cloud/vision'); // don't execute the returned value
const client = new vision.ImageAnnotatorClient();
```

In any case, I'm glad it's working now and that you opened the issue to point out the confusion. We should definitely not be making it so difficult to get started.

**Comment by squarenotch** [comment]
Thanks for looking into it. I did try it without the extra parenthesis and still the same error. I wonder why... It wasn't until I switched to v1 and updated the package.json file did everything snap into place. Most examples I found don't mention v1. I worked it out by looking through the source code in the git repository. Where there is a will.....

Thanks again.

**Comment by jmdobry** [comment]
The docs have all been updated, including the samples in and around https://cloud.google.com/vision/docs/reference/libraries and https://cloud.google.com/nodejs/docs/reference/vision/latest

**Comment by sandrapavankumar** [comment]
I still face the same error with the updated version, can someone please provide the accurate solution.
Thanks

**Comment by JustinBeckwith** [comment]
Greetings @sandrapavankumar!  Can you please open a new issue, with:
- The version of the library you're using 
- The exact code you're using to instantiate the client

Thanks!
