### ISSUE TITLE
Google vision api grpc error for linux environment

### ISSUE THREAD

**Issue by FintechITSolutions** [googleapis/nodejs-vision#211]
npm install --save @google-cloud/vision runs for windows properly but it does not install node-gyp for linux, It gives error :
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v57-linux-x64-glib
Found: [node-v57-win32-x64-unknown]

**Comment by stephenplusplus** [comment]
This issue was moved to grpc/grpc-node#564
