### ISSUE TITLE
Google Cloud Vision built with Webpack

### ISSUE THREAD

**Issue by teq-thuynguyen** [googleapis/nodejs-vision#216]
Dear everyone,

My project is using ReactJS, then I want to use Google-Cloud-Vision to check Identity Card.
But when I added @google-cloud/vision like below tutorial
https://cloud.google.com/vision/docs/libraries#client-libraries-usage-nodejs
I faced the problem is: 

```
./node_modules/grpc/node_modules/node-pre-gyp/lib/util/versioning.js
17:20-67 Critical dependency: the request of a dependency is an expression

./node_modules/grpc/node_modules/node-pre-gyp/lib/pre-binding.js
20:22-48 Critical dependency: the request of a dependency is an expression

./node_modules/grpc/src/grpc_extension.js
32:12-33 Critical dependency: the request of a dependency is an expression

./node_modules/http2/lib/protocol/index.js
46:12-19 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

and I can see  that `@google-cloud/vision` is require [http2](https://yarnpkg.com/en/package/http2) , but this library has been `DEPRECATED`.

Please help me to resolve this problem.

Thanks & Best Regards

**Comment by meredithslota** [comment]
Hi there — thanks for this request! We are about to migrate this library code into the main `google-cloud-node` repo and there is already an existing feature request in that repo for general Webpack support, here: https://github.com/googleapis/google-cloud-node/issues/2933 I'm going to close this issue out in favor of that one.
