### ISSUE TITLE
We can not access the URL currently. Please download the content and pass it in

### ISSUE THREAD

**Issue by sahiramt** [googleapis/nodejs-vision#236]
Hi, 

When trying to extract text from images, the API is giving following error.

**Error:** 

[{"faceAnnotations":[],"landmarkAnnotations":[],"logoAnnotations":[],"labelAnnotations":[],"textAnnotations":[],"localizedObjectAnnotations":[],"safeSearchAnnotation":null,"imagePropertiesAnnotation":null,"error":{"details":[],"code":14,"message":"We can not access the URL currently. Please download the content and pass it in."},"cropHintsAnnotation":null,"fullTextAnnotation":null,"webDetection":null,"context":null}]

Sometimes am getting the correct API response, sometimes not. It was working fine before but today am getting "We can not access the URL currently. Please download the content and pass it in." a lot. Can you please check the issue and let me know how to fix it. 

**Sample code:** 

```
client
.documentTextDetection('https://samsung-nudge.s3.eu-central-1.amazonaws.com/c.jpeg')
.then(results => {
	console.log('results', JSON.stringify(results));
	resolve(results);
})
.catch(err => {
	console.error('GOOGLE VISION ERROR:', err);
	reject(err)
});
```

  - Linux:
  - Node 8
  - npm version: 5.6.0
  - `@google-cloud/vision` version: 0.22.1

**Comment by stephenplusplus** [comment]
I've tested with this URL, and it seems to work. That would indicate to me the server (either the one hosting the image, or Google's API processing server) was having a temporary outage.
