### ISSUE TITLE
Inconsistent OCR text extraction response  

### ISSUE THREAD

**Issue by dibeesh** [googleapis/nodejs-vision#247]
Hi, 

I am using Google vision 'documentTextDetection' for one of my projects. My aim is to detect text from images while checking I get the impression that am getting inconsistent text extraction for same images(ie different link, but image is same) and getting different results. 

I am using '@google-cloud/vision' node npm for the same. Also noticed that some of the characters are mismatching in the results 

eg: In most of the cases '0' is recognizing as O(https://samsung-nudge.s3.eu-central-1.amazonaws.com/4.jpeg), 5 as S (https://samsung-nudge.s3.eu-central-1.amazonaws.com/4.jpeg), / as I (https://samsung-nudge.s3.eu-central-1.amazonaws.com/1.jpeg), etc 

```
let imageurl= 'https://samsung-nudge.s3.eu-central-1.amazonaws.com/barcode1540752102759.jpeg'
client
.documentTextDetection(imageurl)
.then(results => {
	   console.log('results', JSON.stringify(results[0].textAnnotations))
})
.catch(err => {
	console.error('GOOGLE VISION ERROR:', err);
	reject(err)
});
```

**Same image giving different results** 

https://samsung-nudge.s3.eu-central-1.amazonaws.com/barcode1540752102759.jpeg

> MODEL:\nRH60H8138WZ\nPOWER:\n230V/ 50Hz\nCOMPRESSOR:\n2007 - 000029\nMODEL CODE:\nRH6OH8138WZ/SS\nSERIAL NO:\n07KH43AG300046M\n

https://samsung-nudge.s3.eu-central-1.amazonaws.com/m.jpeg

> MODEL:\nRH60H8138WZ\nPOWER:\n230V/ 50Hz\nCOMPRESSOR:\n2007 - 000029\nMODEL CODE:\nRH60H8138WZ/SS\nSERIAL NO:\n07KH43AG300046M\n

Please let me know why am getting inconsistent responses? Also, let me know anything I can do to improve the results.

**Comment by stephenplusplus** [comment]
Unfortunately, this isn't something we can control inside of this library. We are simply passing the image to the upstream service, and returning its response to the user. Members of the API team tend to visit the links mentioned on the Vision support page: https://cloud.google.com/vision/docs/support. Please try reaching out one of those ways for the quickest response.
