### ISSUE TITLE
Cannot find module \'redis\'

### ISSUE THREAD

**Issue by TLKG** [googleapis/nodejs-vision#256]
VSC, ran this in powershell:

`npm run samples-test`

got 

```
C:\nodejs-vision-master\samples\system-test\textDetection.test.js:25
   24: test.cb(`should detect texts`, t => {
   25:   const redis = require('redis');
   26:   const client = redis.createClient();

  Error thrown in test:

  Error {
    code: 'MODULE_NOT_FOUND',
    message: 'Cannot find module \'redis\'',
  }

```

**Comment by TLKG** [comment]
Still the same after another `npm install`

**Comment by JustinBeckwith** [comment]
Greetings!  Can you try the following?

```
$ rm -rf node_modules package-lock.json samples/node_modules samples/package-lock.json
$ npm install
$ cd samples
$ npm install
$ cd ../
$ npm run samples-test
```

If all that doesn't work, please share the output of:
```
$ node -v
```

Thanks!

**Comment by TLKG** [comment]
got err from `rm`:
Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
At line:1 char:5
+  rm -rf node_modules package-lock.json samples/node_modules samples/p ...
+     ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by TLKG** [comment]
Using nvm, now node version is v10.8.0

**Comment by TLKG** [comment]
I'm using nvm and MS' VSC, node version is v10.8.0. anyway, here is the result of first command:
```
rm -rf node_modules package-lock.json samples/node_modules samples/package-lock.json
Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
At line:1 char:4
+ rm -rf node_modules package-lock.json samples/node_modules samples/pa ...
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
```

**Comment by JustinBeckwith** [comment]
Sorry, I'm struggling to figure out how to delete directories in PowerShell myself 😆  @jskeet or @amanda-tarafa can one of y'all translate `rm -rf node_modules package-lock.json samples/node_modules samples/package-lock.json` into PowerShell ?

**Comment by TLKG** [comment]
Justin, what version of node is expected?

**Comment by JustinBeckwith** [comment]
Greetings @TLKG!  Were you able to work through the problem?  Still need help?
