### ISSUE TITLE
Product Search tests are failing

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/nodejs-vision#266]
The Product Search tests have not been running on CI and they weren't running from `npm test` either

I moved all of the `./samples/productSearch/system-test/` tests into `./samples/system-test/` and they're running now, but **failing** ⚠️

I played around to get them passing for a bit, but wasn't able to quickly resolve all of the failures

Filing an issue for someone to pick this up

See related PR which makes the tests actually run!

Set to `[DO NOT MERGE]` because the tests are failing

**Comment by beccasaurus** [comment]
See this PR – tiny changes to get the tests running (for whoever picks up the issue)

https://github.com/googleapis/nodejs-vision/pull/267

Happy to delete this asap once I get an ACK from someone who's picking up the issue

**Comment by beccasaurus** [comment]
Just wanted to share this diff, @nirupa-kumar taking a look at failures – closing! :)

**Comment by beccasaurus** [comment]
Whoops, issue not PR

**Comment by nirupa-kumar** [comment]
working on this.

**Comment by nirupa-kumar** [comment]
Fixed all the issues - pending 1 - Indexed Product Set search - Looks like a permission issue - Looking into it.

**Comment by nirupa-kumar** [comment]
All issues have been fixed and code merged into master.
