### ISSUE TITLE
Vision 'detect' not returning values from remote url since 0.90.0

### ISSUE THREAD

**Issue by Jasonspd** [googleapis/nodejs-vision#270]
Follow this closed issue #2087 , I tried different versions of vision to see when it starts happening.

I was running vision 0.70.0 and install vision like this:
```
npm install google-cloud --save
var gcloud = require('google-cloud');
var vision = gcloud.vision();
```
And it detects remote URL's like a charm.

Since hearing this way of installing google-cloud is deprecated, I tried installing the bundle `@google-cloud/vision`. That's when I encountered the same error as the closed issue. Looking closely, the new install updated my version of vision. I tried 0.70.0 and 0.80.0 which works fine.

From 0.90.0 remote URL detects gives this error:
```
PartialFailureError: A failure occurred during this request.
    at /Users/jasonluu/Documents/v2/node_modules/@google-cloud/vision/src/index.js:420:15
    at /Users/jasonluu/Documents/v2/node_modules/@google-cloud/vision/src/index.js:121:5
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
```
errors: 
   [ { code: 500,
       message: 'image-annotator::error(12): We can not access the URL currently. Please download the image and pass it in.',
       type: 'labels' } ] }
```

**Comment by kinwa91** [comment]
ping @stephenplusplus

**Comment by stephenplusplus** [comment]
@kinwa91 I think we need someone from the backend to take a look, see https://github.com/googleapis/nodejs-vision/issues/270#issuecomment-408960085.

> @JustinBeckwith @swayam18 is providing a URL for analysis to Vision, and sometimes he gets an error from the API (not ours) that the URL cannot be accessed. Should we pass this report and the URL along to the Vision team for further review?

**Comment by sduskis** [comment]
Please see the vision support page for various ways to contact the Vision service support and  team: https://cloud.google.com/vision/docs/support.

**Comment by stephenplusplus** [comment]
@JustinBeckwith @kinwa91 @sduskis -- do you think someone from the Vision team should take a look? Multiple users are reporting intermittent success with the same URL. Would you prefer they each got in touch individually with the Vision support team via the methods on their [Support page](https://cloud.google.com/vision/docs/support)?

**Comment by JustinBeckwith** [comment]
@googleapis/ml-apis @beccasaurus is this something y'all could take a look at?

**Comment by beccasaurus** [comment]
I will try to reproduce this.

FYI the `google-cloud` package is [deprecated](https://www.npmjs.com/package/google-cloud)

Please use `@google-cloud/vision`. See [Using Client Libraries](https://cloud.google.com/vision/docs/quickstart-client-libraries) in the Cloud Vision documentation. We have a Node.js sample for detecting text here: [Text Detection](https://cloud.google.com/vision/docs/detecting-text)

I will try to test using these remote files (in Node and a second language) to see if it's an API problem.

**Comment by gabrielhase** [comment]
We are having the same issue. Our images are on Amazon S3. Uploading them to Google Cloud storage separately just because there is a bug with the Google Vision API sounds wrong... Base64 is not an option right now since we are processing it all in a request. Setting up job queues just for this also sounds very overkill... I am afraid, we'll probably just switch to Amazon Rekognition if this bug persists.

**Comment by beccasaurus** [comment]
I'll reach out to the product team ~

**Comment by beccasaurus** [comment]
> When fetching images from HTTP/HTTPS URLs, Google cannot guarantee that the request will be completed. Your request may fail if the specified host denies the request (e.g. due to request throttling or DOS prevention), or if Google throttles requests to the site for abuse prevention. You should not depend on externally-hosted images for production applications.

----

If you want to use [`image.source.imageUri`][0] in your application, you need to account for the [Cloud Vision API][] occasionally (_or frequently, depending on your QPS and the hosts)_ returning with the error:

> We can not access the URL currently. Please download the image and pass it in.

"Why? That sounds broken! I don't understand!?"

After reading lots of use-cases and user issues, I discovered that it comes down to two limitations:

 1. Being throttled by the website which Cloud Vision is making HTTP requests to for getting the image, which is controlled by the remote host, and avoiding DOS'ing their website
 2. General throttling of the Cloud Vision API endpoint per [Quotas and Limits](https://cloud.google.com/vision/quotas)

After some digging around, I found various references to the documentation of the `imageUri` parameter, from the actual [comment][] on the `imageUri`:
 - REST [reference](https://cloud.google.com/vision/docs/reference/rest/v1/images/annotate#ImageSource.FIELDS.image_uri) of `ImageSource.imageUri`
 - RPC [reference](https://cloud.google.com/vision/docs/reference/rpc/google.cloud.vision.v1#google.cloud.vision.v1.ImageSource.FIELDS.string.google.cloud.vision.v1.ImageSource.image_uri) of `ImageSource.image_uri`

![Screen Shot 2019-04-08 at 5 48 01 PM](https://user-images.githubusercontent.com/280/55765857-99f8fe80-5a26-11e9-9b21-32d02f0c1bad.png)

----

<img src="https://user-images.githubusercontent.com/280/55766300-f6f5b400-5a28-11e9-9552-e2f61f796812.png" alt="Google Cloud Platform logo" title="Cloud Vision How-to Guides" align="left" height="133" width="162"/>

To help users in the future who are learning to use the [Cloud Vision API][], I added this information to the main page which describes how to [Make a Request][], specifically in the section describing how to [provide the image][0] as either a base64-encoded string (`image.content`) or a URI to an image in Google Cloud Storage or HTTP(S) URL (`image.source.imageUri`):

----

Updated website page:

![Screen Shot 2019-04-08 at 5 52 51 PM](https://user-images.githubusercontent.com/280/55765957-2efbf780-5a27-11e9-8c5b-5ba6c9a82fd6.png)

----

**I hope this helps to explain the reason for these errors!**

There are various workarounds which may or may not work for you, depending on your application:

_(in no particular order)_:
 1. Using [truncated exponential backoff][], which is a standard error handling strategy  
  ([example implementations](https://cloud.google.com/storage/docs/exponential-backoff#example_implementations))

 2. Provide the image as a base64-encoded string to `image.content`
  ([base64-encoding instructions](https://cloud.google.com/vision/docs/base64) for various platforms)

 3. Provide the image from Google Cloud Storage  
  ([Migrating from Amazon S3 to Cloud Storage](https://cloud.google.com/storage/docs/migrating) may be useful if you choose this route)

_Hope this helps!_

[Cloud Vision API]: https://cloud.google.com/vision/docs/request
[0]: https://cloud.google.com/vision/docs/request#providing_the_image
[comment]: https://github.com/googleapis/googleapis/blob/2a18b58835c0975a6665671a1ac76ff857ea069f/google/cloud/vision/v1/image_annotator.proto#L149-L154
[Make a Request]: https://cloud.google.com/vision/docs/request
[truncated exponential backoff]: https://cloud.google.com/storage/docs/exponential-backoff

**Comment by gabrielhase** [comment]
Thanks a lot for the detailed answer! I think this might actually help. In addition to having original images on S3 we deliver them through a CDN image service (ImgIX) which shouldn't tremble from a few requests :) Also, I read that the Vision API is downsampling to 224x224 anways. With the image service URLs we can downsample on our side which should further alleviate the throttling issue. I'll give it a try 👍
