### ISSUE TITLE
Face detection  test failure

### ISSUE THREAD

**Issue by nirupa-kumar** [googleapis/nodejs-vision#277]
#### Environment details
 While running tests in automation with Kokoro
  - OS: NA
  - Node.js version:NA
  - npm version:NA
  - `@google-cloud/vision` version: 0.23.0

#### Steps to reproduce

  1. Create a new PR [https://github.com/googleapis/nodejs-vision/pull/269]
  2. Automated tests get triggered with Kokoro and the sample tests fail.
This does fail locally too.

Tried debugging the issue 
- first it was looking for a directory that did not exist `vision` : Fixed that
- next got an error `Canvas is not a constructor`

**Comment by beccasaurus** [comment]
I got it working locally by `npm install canvas`

Here are the docs for the Face Detection tutorial:
https://cloud.google.com/vision/docs/face-tutorial

![screen shot 2018-11-28 at 2 02 40 pm](https://user-images.githubusercontent.com/280/49185247-4fe46b80-f316-11e8-81ff-45c1efb55d90.png)

Does our CI server script `npm install canvas` anywhere?

Doing an `npm install` does not work by itself, it blew up for me until I ran `npm install canvas`

**Comment by nirupa-kumar** [comment]
This has been fixed as part of https://github.com/googleapis/nodejs-vision/pull/269 
Needed two changes:
- update the package.json file in the samples directory to include canvas as part of the dependencies. 
- update the faceDetection.js file to use the new format for calling the Canvas constructor
