### ISSUE TITLE
Question regarding safe search free with label detection

### ISSUE THREAD

**Issue by Dayjo** [googleapis/nodejs-vision#281]
So on the pricing page for google vision there's this section;

![](http://c.dayjo.me/ce94dcee22fc/Image%202018-11-30%20at%204.37.36%20pm.png)

Which states that safe search detection is free with label detection, however I cannot see any way using the SDK to make a request for both labels and safe search in one. Doing them separately at the moment, and in the console the stats are saying that there are 2 calls (which presumably we'll get charged for eventually).

Am I missing something here, is there actually a way to do this with the SDK.

**Comment by kinwa91** [comment]
You'll need to make a single request like this:

```javascript
const vision = require('@google-cloud/vision');
const client = new vision.v1.ImageAnnotatorClient();

const request = {
  image: {
    ...
  },
  features: [
    {
      type: client.features.LABEL_DETECTION,
    },
    {
      type: client.features.SAFE_SEARCH_DETECTION,
    }
  ]
}

client.annotateImage(request)
  .then(...
```

**Comment by Dayjo** [comment]
This is super useful @kinwa91, thank you. I highly recommend adding this somewhere in the documentation :)
