### ISSUE TITLE
Methods should be in verb form, not noun form.

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/nodejs-vision#3]
As part of moving to Vision partials, the single-feature methods changed from verb form (`detectFaces`) to noun form (`faceDetection`).

The reason for this is that when I originally wrote this and those methods were dynamically applied, I used the value in the enum. So, the `Feature.Type` enum in the proto has `FACE_DETECTION`, and I converted it to camelCase and applied it to the class. I did some experimentation to try and keep it in verb form (e.g. `detectFaces` or even `detectFace`) but ultimately did not feel confident that it could work. The enum values were not sufficiently consistent to do that reliably, pluralizing words automatically is hard, etc.

@jgeewax has suggested a few ideas:

 #### A one-liner in the client library written manually.

I am cynical about this. It sounds attractive and I went over several iterations on it, but I ultimately decided it was probably going to cause more problems than it solved. Basically, it relies on domain knowledge being carried forward indefinitely, potentially by people unfamiliar with the rationale. If that breaks down (and I expect it will), then you end up in a situation where you have inconsistent methods or features with no helper methods at all.

#### A proto annotation.

I think this would work really well.

#### Configuration checked in alongside the proto that the ML team maintains.

I am skeptical about this. I think it is likely to end up in a situation where we have features with no helper method at all, which feels like a bigger quality loss in the long run.

**Comment by jgeewax** [comment]
Note that config (yaml) next to the proto is another way or storing annotations which is in use by several teams.

> Configuration checked in alongside the proto that the ML team maintains.
> I am skeptical about this. I think it is likely to end up in a situation where we have features with no helper method at all, which feels like a bigger quality loss in the long run.

That will be the producing team's job -- if they don't want one, they don't get one. If they forget, then they have to notice and fix it the same way they have to remember to have the correct HTTP mapping on their RPCs (which is forgotten from time to time).

**Comment by lukesneeringer** [comment]
Okay, if there is precedent, then I am a lot more sanguine about going that route.

**Comment by stephenplusplus** [comment]
It sounds like the first step is to get a proto annotation or config yaml prepared for us. How do we get that started?

**Comment by JustinBeckwith** [comment]
Just so I remember what this is - chatted with @alexander-fenster, and it looks like the offending code is actually in `helpers.js`, which is hand crafted.   I believe the fix here is to add new helpers with better names, and update the samples.  Ideally, we would keep back-compat while doing this.

**Comment by JustinBeckwith** [comment]
@stephenplusplus you previously had context here - does this sound right?

**Comment by sduskis** [comment]
@callmehiphop, is this something you can work on?

**Comment by bcoe** [comment]
closing upon @lukesneeringer's direction.
