### ISSUE TITLE
Request to document the `credentials` parameter

### ISSUE THREAD

**Issue by tlhunter** [googleapis/nodejs-vision#308]
When using the GCF UI to generate a key for google vision I am provided with a JSON file. However, this repository doesn't state how to use the JSON file.

I believe the documentation for this repo would increase greatly by adding the following code sample to the README:

```javascript
const vision = require('@google-cloud/vision');
const credentials = require('./vision-grpc-test-google-api-keys-3aa2156ccb74.json');

// Creates a client
const client = new vision.ImageAnnotatorClient({
  credentials
});
```

Without this code sample the example in the README would fail as the user isn't authenticated. One needs to either install and configure `gcloud`, use the `GOOGLE_APPLICATION_CREDENTIALS` environment variable (another great README candidate), or hunt down the `credentials` parameter (I discovered it in #63).

One can eventually come across the above documentation, but adding it to the README would help reduce friction for new users.

**Comment by Komsomol** [comment]
Thank you. It's silly this is not documented on the platform or the official documentation.

**Comment by stephenplusplus** [comment]
@JustinBeckwith how could we do this? Across the repos, the readme should at least show the `keyFilename` option (PS @tlhunter, `credentials` is fine, but `keyFilename: './vision-grpc-test-google-api-keys-3aa2156ccb74.json'` works, too).

**Comment by JustinBeckwith** [comment]
@crwilcox @theacodes how do you document this for the Pythons?

**Comment by nnegrey** [comment]
Python typically points toward the cloud docs for set up info.

**Comment by sgreenberg** [comment]
This issue has been open for awhile and since then the docs have improved quite a bit here. Both the README in this repo and the intro text before each sample on cloud.google.com point pretty quickly to https://cloud.google.com/docs/authentication/getting-started which is a good guide for auth. 

I'm going to close this out, but if I'm not understanding the problem correctly, please feel free to reopen.
