### ISSUE TITLE
When will Vision types be available [Typescript]

### ISSUE THREAD

**Issue by fenixsolorzano** [googleapis/nodejs-vision#311]
It would be truly helpful (actually it's necessary) to have types declared for using Vision in typescript projects, Im currently creating Firebase Cloud Functions in typescript but the ones related to Vision are harder to make without types.

**Comment by JustinBeckwith** [comment]
Greetings!  We're working on auto-generating our libraries in TypeScript, but we don't know when it will be done quite yet :) As we make progress - we'll update this issue!

**Comment by rscotten** [comment]
yes, please add TS types.  Thanks!

**Comment by katbusch** [comment]
Excited to hear, thanks!

Any updates on the timeline here?

**Comment by janicerar** [comment]
Any update?

**Comment by charliemcgrady** [comment]
+1 on official typings.

I have somewhat worked around the problem by adapting [these types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gapi.client.vision/index.d.ts) - https://gist.github.com/charliemcgrady/bf5c8ce6591e9cbb0015a70d16f0ea49

```
  import { AnnotateImageResponse, AnnotateImageRequest } from "./vision-types";
  const client = new vision.ImageAnnotatorClient();
  const response: Array<AnnotateImageResponse> = await client.annotateImage({...} as AnnotateImageRequest);
```

**Comment by bcoe** [comment]
I can't commit to a timeline just yet, but we've generated our first few libraries now with TypeScript support, so soon.
