### ISSUE TITLE
Label Detection only returns labels few times with service key and gcs path

### ISSUE THREAD

**Issue by ksangha1** [googleapis/nodejs-vision#357]
I'm using the Label Detection feature for my project. At first I was providing Google Signed URLs for images stored in my Google Storage bucket but this led to issues where majority of the time there were no labels returned and the error message:
 > Did not find Labels due to possible error: The URL does not appear to be accessible by us. Please double check or download the content and pass it in. 

I read the note regarding HTTP/HTTPS URLs and then provided a path to the storage object with my bucket name and a service key as part of the options objects for the vision client. Yet I still see issues where sending the API a request this way still results in only receiving labels very few times. Majority of the requests result in the 
> unable to open file gs://{bucketname}/{file_path}

 even though some requests do return succesfully with the provided service key which has full(read/write) access to the bucket.

Using  "@google-cloud/vision": "^0.25.0"

I've provided the following snippet: 

```js
const options = {keyFilename: keyFilename};
const client = new vision.ImageAnnotatorClient(options);
              
let request = {image:{source:{imageUri: uri}}};
 
client.labelDetection(request).then(function (result)
```

**Comment by callmehiphop** [comment]
Hi @ksangha1 which API version are you trying to use (v1, v1beta1, etc.)? We have tests for label detection that are working well enough. My best guess with the details provided is that there is likely a permissions issue with your bucket.

**Comment by ksangha1** [comment]
I'm using v1 and the service key i provide for the options object has Read/Write permissions for the bucket. I thought it was a permissions issue earlier but a few times the request with the uri for the images stored in that bucket are successfully returning labels but majority of the time same bucket stored image being sent as a request results in no labels and the unable to open file error.

**Comment by nnegrey** [comment]
Very delayed response. 
For images stored in GCS, you need to use gcs_image_uri in ImageSource
https://cloud.google.com/vision/docs/reference/rpc/google.cloud.vision.v1p4beta1#imagesource
