### ISSUE TITLE
OCR ignores many single-character words

### ISSUE THREAD

**Issue by bfla** [googleapis/nodejs-vision#36]
Hi,

Google Vision's "Document Text Detection" is a great product!  I lead an engineering team at a startup, which uses Google Vision to extract text from 1+ million PDF pages per month.  For the most part, we are very happy with the service and we look forward to using it to analyze many millions of images over the coming months.

For our use case, there is one huge problem with the OCR output we get from Google Vision:  it often omits single characters which appear by themselves.  Common examples:
- "$" with a space between the dollar sign and the number that goes with it
- "0" the number zero, when presented as a single character
- "C" the letter C, when used as a single-letter abbreviation
- "O" the letter O, when presented as a single-letter abbreviation

These characters are actually very important information for my use case.  Other OCR products like Tesseract and ABBYY correctly read and present these characters while Google Vision does not, which leads me to suspect that Google Vision might have been intentionally trained or programmed to exclude these from its output.  Is it likely that this will be fixed in the near future?  (If not, I might need to invest my team's resources into building a workaround.)

**Comment by stephenplusplus** [comment]
That's interesting, I haven't heard of it before. This is a better question for the Vision team-- we are just the client library that wraps their API. You can see better ways to reach them here: https://cloud.google.com/vision/docs/support. Sorry I can't be more help.

**Comment by bfla** [comment]
Thanks!  I'll try my luck with them.  Nice work on the node library!  You guys have been making helpful changes the last few months!

**Comment by stephenplusplus** [comment]
Thank you 🙏! Feel free to come back and let us know if you find any answers.
