### ISSUE TITLE
Failing sample tests

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/nodejs-vision#372]
The sample test for importing a product set using `gs://nodejs-docs-samples/product-search/product_sets.csv` is failing with the following error:

```
{
  Error: The number of columns in the csv line should be 8, but the detected number of columns is 6 on line 1:
      "gs://nodejs-docs-samples/product-search/shoes_1.jpg",
      "fake_product_set_id_for_testing",
      "fake_product_id_for_testing_1",
      "apparel",
      "style=womens",
      "0.1,0.1,0.9,0.1,0.9,0.9,0.1,0.9".
    at Operation._unpackResponse (/tmpfs/src/github/nodejs-vision/node_modules/google-gax/build/src/longRunningCalls/longrunning.js:144:31)
    at noCallbackPromise.currentCallPromise_.then.responses (/tmpfs/src/github/nodejs-vision/node_modules/google-gax/build/src/longRunningCalls/longrunning.js:130:18) code: 3
}
```

Looking at the vision docs, 8 columns are required and this appears to be non-configurable. I'm not sure if we should be using that CSV file or if the latest version is malformed, etc. But it seems like we probably want to do one of the following:

1. Fix the CSV file (not sure who owns that Bucket?)
2. Add a new CSV file to the repo to use as a test fixture

**Comment by callmehiphop** [comment]
@bcoe @beccasaurus any thoughts here?

**Comment by beccasaurus** [comment]
The sample needs to be updated to use gs://cloud-samples-data/vision/
(per @dizcology)

**Comment by dizcology** [comment]
Pointing to the updated csv here should fix the issue: `gs://cloud-samples-data/vision/product_search/product_sets.csv`.

**Comment by callmehiphop** [comment]
@beccasaurus @dizcology awesome, thanks!
