### ISSUE TITLE
lodash.merge suffers prototype pollution

### ISSUE THREAD

**Issue by gabegorelick** [googleapis/nodejs-vision#381]
`lodash.merge` v4.6.1 suffers from prototype pollution (https://snyk.io/vuln/SNYK-JS-LODASHMERGE-173732). The recommendation from upstream is to use `lodash` directly since there is no newer version of `lodash.merge` published. See https://github.com/lodash/lodash/issues/4193#issuecomment-463247496.

**Comment by alexander-fenster** [comment]
First step: https://github.com/googleapis/gax-nodejs/pull/503
After this is merged and released, I'll replace calls to `merge` with passing `[list of protos]` to `gaxGrpc.loadProto`.

**Comment by alexander-fenster** [comment]
To give some more details, the call to `lodash.merge` in our code only takes known objects coming from [Protobuf.js](https://github.com/protobufjs/protobuf.js) as parameters so prototype pollution is highly unlikely in this case. Anyway, we'll remove calls to `merge` in this case.

**Comment by alexander-fenster** [comment]
@gabegorelick Thanks - your report was a kind of the last straw that made us stop using `lodash.merge` in the generated code :)  Fixed in #384 and will be released soon.
