### ISSUE TITLE
Stale link in textDetection.js sample file

### ISSUE THREAD

**Issue by gondar00** [googleapis/nodejs-vision#396]
https://github.com/googleapis/nodejs-vision/blob/master/samples/textDetection.js#L32

The link specified leads to a 404 page

**Comment by bcoe** [comment]
@gondar00 any interest in submitting a patch for your fix? I'd happily land it for you.

Otherwise this ticket is triaged now, thank you for reporting the issue.

**Comment by gondar00** [comment]
Sure @bcoe done 👍
