### ISSUE TITLE
Node engine issue with Cloud Functions for Firebase

### ISSUE THREAD

**Issue by jasonberryman** [googleapis/nodejs-vision#409]
#### Environment details

  - OS: Cloud Function for Firebase
  - Node.js version: 10
  - npm version: 6.9.2
  - `@google-cloud/vision` version: 1.1.3

#### The error
  `Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0`

#### Steps to reproduce

  1. Create a project in Firebase with support for Cloud Functions and Javascript
  2. Set the Node version in `package.json` to `10`
  3. Run `npm install --save @google-cloud/vision@latest`
  4. Edit `index.js` and add the following lines:

```
const Vision = require('@google-cloud/vision');
const vision = new Vision.ImageAnnotationClient();
```

  5. Run `firebase deploy --only functions`

#### Attempts to resolve

  1. Set the `engines/node` in `package.json` to `10.15.3`.  Firebase reports that the only supported values are 8 or 10.
  2. Can I use the `--ignore-engines` parameter in Yarn when installing the vision package?

**Comment by jasonberryman** [comment]
There is also a similar issue with nodejs-logger, which can be seen here https://github.com/googleapis/nodejs-logging/issues/523

**Comment by jasonberryman** [comment]
I have found a workaround...

Instead of requiring the module at the global level (at the top of index.js), I've required it within the function that consumes the Vision API.  This resolves the issue and lazy loads the Vision API, so that it is only used for the functions that need it.

However, this doesn't fix it for anyone that needs to require the module outside of a function.

**Comment by JustinBeckwith** [comment]
@bcoe this looks like a bad bug with Cloud functions

**Comment by bcoe** [comment]
@jasonberryman what version of Node 10 are you running locally; using the latest version of `firebase-tools` (`7.0.2`) and Node.js `v10.15.3`, I'm able to deploy your example:

```js
const functions = require('firebase-functions');
const Vision = require('@google-cloud/vision');
const vision = new Vision.ImageAnnotatorClient();

// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions
//
exports.helloWorld = functions.https.onRequest((request, response) => {
  console.log(typeof vision, vision);
  response.send("Hello from Firebase!");
});
```

```bash
✔  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (37.73 KB) for uploading
✔  functions: functions folder uploaded successfully
i  functions: updating Node.js 10 (Beta) function helloWorld(us-central1)...
✔  functions[helloWorld(us-central1)]: Successful update operation. 
```

**Comment by JustinBeckwith** [comment]
@jasonberryman hopefully, this is working out :) If you're still having problems, and have any more info to share -  we'd be happy to take another look!
