### ISSUE TITLE
OCR Response different from Demo

### ISSUE THREAD

**Issue by felix-voicehub** [googleapis/nodejs-vision#410]
Hi,

I am trying to understand why the response I am getting from the API using this library is different form the JSON result on the demo (https://cloud.google.com/vision/).
Lets take this image for example:

<img width="50" alt="wurst" src="https://user-images.githubusercontent.com/49151885/61798537-be3be800-ae29-11e9-8113-9fef632e0459.png">

[link](https://user-images.githubusercontent.com/49151885/61798537-be3be800-ae29-11e9-8113-9fef632e0459.png)

With the example code (https://cloud.google.com/vision/docs/ocr#detect_text_in_a_local_image) I am getting for every `text` result a `confidence` of 0, also the `locale` is empty for every single element.

With the demo however, there are values for each of these if you open the JSON dropdown below the demo. Why is there a difference here?

#### Environment details

  - OS: macOS Mojave
  - Node.js version: 10.14.1
  - npm version: 6.10.2
  - `@google-cloud/vision` version: 1.1.3

#### Steps to reproduce

  1. Get the example code from the link above
  2. Use my provided Image
  3. Compare the results of the printed response from this library with the JSON from the demo page

**Comment by habib-Boloorchi** [comment]
I think if you add: .v1 to this line of code 'const vision = require('@google-cloud/vision').v1;'  it works:
and it will also solve many other problem.
I think you need also use this 'client.documentTextDetection(`gs://${bucketName}/${filename}`)' instead of '.textDetection(`gs://${bucketName}/${filename}`)'
hope it goes well.

**Comment by felix-voicehub** [comment]
Hm, doesn't look like this changed much for me.

**Comment by callmehiphop** [comment]
@felix-voicehub looks like in the Node.js sample you're referencing it uses the `textAnnotations` field of the response, but it would appear that the vision demo is using `fullTextAnnotations` field instead.

**Comment by Louis345** [comment]
@callmehiphop  how do I use the fullTextAnnotations. When attempting to the method I get a typeError ```TypeError: client.fullTextAnnotations is not a function````

**Comment by callmehiphop** [comment]
@Louis345 interesting, would you be willing to open a new issue that contained some code to reproduce the issue you are seeing?

**Comment by Louis345** [comment]
@callmehiphop  I figured it out. FullTextAnnotation is a response, not a method.

**Comment by stephenplusplus** [comment]
Sounds like everything is working out. Let us know if there's more we can help with!
