### ISSUE TITLE
Google Vision OCR replacing other content than english

### ISSUE THREAD

**Issue by sunnykeerthi** [googleapis/nodejs-vision#421]
I'm trying to extract text from an image using google OCR, but here the issue is, if the text is in other language(Hindi in my case), the content is getting replaced automatically with some random text in English.

Here is the code that I'm trying out with.

```
const vision = require('@google-cloud/vision');
const fs = require('fs');
function exportDetections(fileName, callback) {
    console.log(fileName);
    const client = new vision.ImageAnnotatorClient({
        keyFilename: myKeyJson,

    });

    const request = {
        image: {
            content: fs.readFileSync(fileName),
        },
        "imageContext": {
            "languageHints": [
                "en"
            ]
        }
    };
    client
        .documentTextDetection(request)
        .then(results => {
            const fullTextAnnotation = results[0].fullTextAnnotation;
            console.log(`Full text: ${fullTextAnnotation.text}`);
        })
        .catch(err => {
            console.error('ERROR:', err);
        });
}

exportDetections('./temp/Temp.png');
```

#### Environment details

  - OS: Mac - 10.14.6 
  - Node.js version: v10.16.0
  - npm version: 6.9.0
  - `@google-cloud/vision` version: 1.1.4

#### Steps to reproduce

  1. give Image with Hindi content as input and run it.

Here is the sample Image used

<img width="664" alt="Temp" src="https://user-images.githubusercontent.com/17703864/62938600-f44b0700-bdec-11e9-9857-c50b17eec6fd.png">

Thanks!

**Comment by bcoe** [comment]
@sunnykeerthi have you tried setting `languageHints` to `hi` out of curiosity? your example code shows that you're setting the language to `en`.

**Comment by sunnykeerthi** [comment]
Hi @bcoe ,

Thanks for the quick response and apologies for the delay in responding. Yes you are correct, when I had `hi`, the output is exact as the input (both hindi and english content shows up), but my goal is to extract only English content and ignore the rest.

**Comment by bcoe** [comment]
@sunnykeerthi according to the documentation, vision should be able to detect multiple languages within a single file. Have you tried passing an array to `languageHints`? try:

```
languageHints: ['hi', 'en']
```

**Comment by sunnykeerthi** [comment]
@bcoe , Yes, as mentioned in my response, I was able to get both `hindi` and `english`, by using it in the array format that you gave, but Here in my case I just want to pull `English` content ignoring the `Hindi` part

Thanks

**Comment by nnegrey** [comment]
I don't think the vision api has a way to extract just one language and exclude another. 

You can file a feature request on this page: https://cloud.google.com/support/docs/issue-trackers
