### ISSUE TITLE
sample tests failing

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-vision#449]
sample tests are broken currently on the main branch:

see: https://github.com/googleapis/nodejs-vision/pull/447,
https://github.com/googleapis/nodejs-vision/pull/445

**Comment by stephenplusplus** [comment]
Here's the error:

```js
{ Error: Error opening file: gs://nodejs-docs-samples/product-search/shoes_1.jpg
    at Http2CallStream.call.on (/tmpfs/src/github/nodejs-vision/node_modules/@grpc/grpc-js/build/src/client.js:96:45)
    at Http2CallStream.emit (events.js:203:15)
    at process.nextTick (/tmpfs/src/github/nodejs-vision/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 7,
  details:
   'Error opening file: gs://nodejs-docs-samples/product-search/shoes_1.jpg',
  metadata: Metadata { options: undefined, internalRepr: Map {} } }
```

The credentials to that file (https://storage.googleapis.com/nodejs-docs-samples/product-search/shoes_1.jpg), seem to not be public. Fair enough, but it looks like my service account can't access it either, which makes reproduction harder to figure out. Is it possible permissions were changed, which blocked us all out?

**Comment by callmehiphop** [comment]
I wonder if the resource has been deleted and/or moved. @beccasaurus any insights here?

**Comment by bcoe** [comment]
@callmehiphop hrm, we were seeing this with some other APIs, I could re-upload to our testing account if we have an idea of what the resource was; perhaps let's give @beccasaurus a chance to chime in though :smile:

**Comment by stephenplusplus** [comment]
Related: https://github.com/googleapis/nodejs-vision/issues/449
