### ISSUE TITLE
make samples tests pass

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-vision#49]
Hi Shahin and Ace,

Could you please work on making samples tests for Vision pass? I cannot draft a new library release until the samples tests work, and having them failing affects our nightly builds.

Example: https://circleci.com/gh/googleapis/nodejs-vision/1481

Thanks!

**Comment by happyhuman** [comment]
Hi @alexander-fenster ,
I fixed the issue with PDF/OCR sample code in this PR:
https://github.com/googleapis/nodejs-vision/pull/50

Can you please review it?

**Comment by alexander-fenster** [comment]
Fixed in #50.
