### ISSUE TITLE
Single digit columns not scanned? 

### ISSUE THREAD

**Issue by jordan-lumley** [googleapis/nodejs-vision#498]
#### Environment details

  - OS: Linux Mint 19.2
  - Node.js version:
  - npm version:
  - `@google-cloud/vision` version: 1.7.2

#### Steps to reproduce

  1. None really

Hey all, so I am new to the cloud vision API world. I do have familiarity with tesseract but wanted to take a stab at the cloud vision API. I am using the Node client library. 

Is there any reason why in this document (screenshot below) that the single digit columns are just complete wiped? I have tried both text detect as well as document text detect. "documentTextDetection" does not see that column at all. "textDetection" does see it but not all of them. Maybe the font is too small? 

Is there some configuration settings I can tweak or that I am missing? I have gone through the API docs 2-3 times now. 

![image](https://user-images.githubusercontent.com/57803850/70268909-569a8f80-176f-11ea-937d-6721d3ebbf9f.png)

I also noticed that the order of the returned results don't really make much sense. For the most part its setting the rows in the document/image and reading them in vertically. Some of the items are out of order though. Not sure if this is specifically the node client or Google Cloud Vision. Figured, I'd start here. Example:
REAL IMAGE
![image](https://user-images.githubusercontent.com/57803850/70270526-9f077c80-1772-11ea-9435-24d2656a070b.png)

OCR RENDER (odd order?):
![image](https://user-images.githubusercontent.com/57803850/70270569-b5153d00-1772-11ea-9492-0231d5024846.png)

**Comment by monkidea** [comment]
did anyone find the solution

**Comment by vinnysenthil** [comment]
Closing this issue as the thread has been inactive for over a year. Please re-open if this is still an active issue.
