### ISSUE TITLE
could not find declaration for module '@google-cloud/vision'

### ISSUE THREAD

**Issue by khainhero** [googleapis/nodejs-vision#514]
So i am trying to work with vision api with my firebase cloud functions and I keep getting this error

```
Could not find a declaration file for module '@google-cloud/vision'. 'c:/Users/*****/pushNotification/functions/node_modules/@google-cloud/vision/src/index.js' implicitly has an 'any' type.
  Try `npm install @types/google-cloud__vision` if it exists or add a new declaration (.d.ts) file containing `declare module '@google-cloud/vision';
```
My code:
```
const vision = require("@google-cloud/vision");
const visionClient = new vision.ImageAnnotatorClient();
```
in `const vision = require("@google-cloud/vision");` the `("@` has 3 dots under it specifying the previous error.

  - OS: Windows 10
  - Node.js version: v8.13.0
  - npm version: 6.13.6
  - `@google-cloud/vision` version: 1.8.0

 **I already have the @google-cloud/language API working correctly with no import error**

my package.json:

```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "dependencies": {
    "@google-cloud/language": "^3.7.0",
    "@google-cloud/storage": "^3.5.0",
    "@google-cloud/vision": "^1.8.0",
    "acorn": "^6.4.0",
    "firebase-admin": "8.6.0",
    "firebase-functions": "^3.3.0",
    "firebase-tools": "7.9.0",
    "fs-extra": "^8.1.0",
    "sharp": "^0.23.4"
  },
  "devDependencies": {
    "eslint": "^5.16.0",
    "eslint-plugin-promise": "^4.2.1"
  },
  "private": true
}
```
I did google this problem as its a huge occurrence mostly everywhere but its normally fixed when utilizing typescipt import and converting it to javascript import. 

Thank you in advance.

**Comment by bcoe** [comment]
@khainhero we are in the process of migrating many of our client libraries to TypeScript, doing so might help with this issue.

I would expect switching to the JavaScript import to work, I'm wondering if it's potentially something to do with your TypeScript configuration -- I've reached out to my peers, to see if there's anything blocking us from converting this library to TypeScript.

**Comment by NickFaulkner101** [comment]
Did you find a solution? Same issue here

**Comment by JustinBeckwith** [comment]
This is *super* weird.  Are either of you trying to use TypeScript?  Are you getting this error locally, or when you deploy your function?

**Comment by khainhero** [comment]
> This is _super_ weird. Are either of you trying to use TypeScript? Are you getting this error locally, or when you deploy your function?

No i dont use typescript. I updated to 1.9.0 and updated all related SDK (admin, firebase-tools) and issue still persists. Everything else works (cloud-storage, cloud-language, firebase-admin).

my hierarchy is like following: 

```
>functions
   >node_modules
   .eslintrc.json
   .gitignore
   index.js
   package-lock.json
   package.json
.firebaserc
.gitignore
firebase.json 

```

**Comment by JustinBeckwith** [comment]
Thanks!  Are you getting this issue locally, or when you deploy?  Or both?  How exactly can I reproduce this?

**Comment by khainhero** [comment]
> Thanks! Are you getting this issue locally, or when you deploy? Or both? How exactly can I reproduce this?

oh my

So it deploys, and I just tried safe-search which worked. It seems like this error is locally. Really a cumbersome issue because it doesn't populate "vision" methods so i have to go off copy/pasting from the api/references exactly from documentation

**Comment by john20xdoe** [comment]
For people using Typescript, the intellisense seemed to work by importing like this:

```
import * as vision from '@google-cloud/vision';
import 'google.cloud.vision';
```

**Comment by john20xdoe** [comment]
For people using Typescript, the intellisense seemed to work by importing like this:
```
import * as vision from '@google-cloud/vision';
import 'google.cloud.vision';
```

**Comment by bcoe** [comment]
@khainhero where are now converted to TypeScript and I believe that:

```
import * as vision from '@google-cloud/vision'
```

should work, as @john20xdoe suggests, does this unblock you?
