### ISSUE TITLE
Face Detection Tutorial Issues

### ISSUE THREAD

**Issue by grant** [googleapis/nodejs-vision#54]
There are a few problems with the [cloud vision face tutorial](https://cloud.google.com/vision/docs/face-tutorial):

## Setup

- `canvas` in `optionalDependencies`: This is a required dependency. 
- "Put it all together": This section does not have any description and does not have copy-pasteable code I would expect in an "All together" section.
- `node faceDetection face.png`:

## Running

After the setup, run:
`node faceDetection face.png`

You'll get the error:

```sh
ERROR: { Error: ENOENT: no such file or directory, open 'face.png' errno: -2, code: 'ENOENT', syscall: 'open', path: 'face.png' }
{ Error: ENOENT: no such file or directory, open 'face.png' errno: -2, code: 'ENOENT', syscall: 'open', path: 'face.png' }
^C
```

What you really need is:
`node faceDetection.js resources/face.png`

```
ERROR: { Error: 7 PERMISSION_DENIED: Cloud Vision API has not been used in project cloud-devshell-dev before or it is disabled. Enable it by visiting https://console.developers.googl
e.com/apis/api/vision.googleapis.com/overview?project=cloud-devshell-dev then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems a
nd retry.
```

## Fixing permissions

I tried to enable the Vision API in the Cloud Shell, first trying to find the API:

```sh
gcloud services list

ERROR: (gcloud.services.list) PERMISSION_DENIED: Not allowed to get project settings for project cloud-devshell-dev
```

I'm not sure if I could enable the API without knowing the id. Maybe I needed to create a new project rather than `cloud-devshell-dev`.

Guessing at the API id:

```sh
gcloud services enable vision.googleapis

User does not have permission to access service [vision.googleapis:enable] (or it may not exist): The caller does not have permission.
```

At this point I gave up. It would be ideal if you could just "Open in Cloud Shell", `npm i`, and `npm run detect`.

I first found this tutorial on GitHub. The process of switching between cloud.google.com, GitHub tutorial README, GitHub main README, and Cloud Shell is very confusing.

**Comment by stephenplusplus** [comment]
@alexander-fenster

**Comment by crwilcox** [comment]
@grant , to enable the API you can navigate to the link and click 'enable'.

**Comment by grant** [comment]
@crwilcox @JustinBeckwith When I wrote this issue in April this was a friction log of various issues with the tutorial.

For example, the `face.png` image is in the wrong directory. It should either be moved to `samples/` or the tutorial instructions should be fixed.

It would be awesome if you considered running through the sample to make sure it works. Or link the bug component where I can file a docs issue. That would increase the Cloud Site page's feedback star rating.

**Comment by JustinBeckwith** [comment]
Thanks @grant!  Handling this over to the @googleapis/ml-apis folks to take a look at :)

**Comment by JustinBeckwith** [comment]
*gentle ping* @googleapis/ml-apis & @beccasaurus

**Comment by beccasaurus** [comment]
ACK. We'll incorporate these changes. Thanks for this feedback @grant!

**Comment by dizcology** [comment]
The tutorial page had been updated with correct paths to the image file.  Closing this issue now - please feel free to re-open if you are still experience problems.

**Comment by grant** [comment]
Looks pretty good, but we still need a description for "Put it all together". 
https://cloud.google.com/vision/docs/face-tutorial#put_it_all_together

We can't just have unexplained code snippets.

Something like... `To call our Vision API, create a main method which will...`
