### ISSUE TITLE
Invalid auto-generated type for the ImprovedRequest interface

### ISSUE THREAD

**Issue by ihorTymofieiev** [googleapis/nodejs-vision#549]
#### Environment details

  - OS: MacOs 10.15.3
  - Node.js version: v12.10.0
  - npm version: 6.11.3
  - `@google-cloud/vision` version: 1.10.0

P.S. Also you can try to use node:12.16.1 docker image.
( https://hub.docker.com/_/node )

#### Description 

 Your auto-generated source code is missing some info about the ImprovedRequest interface. You can find the file with this interface in `nodejs-vision/src/helpers.ts`.

You code version:
```
interface ImprovedRequest {
  image?: {source?: {filename: string}; content?: Uint8Array | string | null};
  // tslint:disable-next-line no-any
  features?: any;
}
```
Right code version:
```
iinterface ImprovedRequest {
    image?: {
        source?: {
            filename?: string;
            imageUri?: string;
        };
        content?: Uint8Array | string | null;
    };
    // tslint:disable-next-line no-any
    features?: any;
}
```

You can find the proof of using this property in your source code or in your example - 
`https://github.com/googleapis/nodejs-vision/blob/master/samples/async-batch-annotate-images.js`.

I hope for a quick solution to this issue. Thanks!

**Comment by bcoe** [comment]
@xiaozhenliu-gg5 bother you folks to take a look at this?

**Comment by ihorTymofieiev** [comment]
@xiaozhenliu-gg5 ,  can you look at this?

**Comment by rscotten** [comment]
Plus there's disagreement with the online documentation: 

https://cloud.google.com/vision/docs/reference/rest/v1/AnnotateImageRequest#Image

**Comment by xiaozhenliu-gg5** [comment]
Thanks for pointing this! Actually this one is manually written, not auto-generated. And I double checked the types we use as ImprovedRequest, I think yes `imageUri?: string;` is missing here.

I'm making a quick PR to fix it, thank you! @bcoe @ihorTymofieiev @rscotten
