### ISSUE TITLE
Single-feature methods are not added dynamically.

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/nodejs-vision#6]
The Vision API does not add single-feature methods dynamically the way we intended it to do.

Instead, the structure is in place, but due to documentation restrictions, we still manually define each method. This means that when the enum is expanded, new methods will not be defined.

We should write a JSDoc plugin so appropriate documentation is automatically generated, then iterate over the enum.

**Comment by stephenplusplus** [comment]
@JustinBeckwith do you think this is something that would ever happen? :)

**Comment by JustinBeckwith** [comment]
Probably not 🙃
