### ISSUE TITLE
Configure vision client with API key?

### ISSUE THREAD

**Issue by ryanwalters** [googleapis/nodejs-vision#63]
#### Environment details

  - OS: Mac OS
  - Node.js version: 8.11.1
  - npm version: 5.6.0
  - `@google-cloud/vision` version: 0.19.0

#### Steps to reproduce

None, this is a question.

#### Question

Is it possible to configure the vision client with an API key rather than a Credentials object?

Our use case does not allow us checking in a credentials.json file into the repository, but we are able to use environment variables. It would be nice to be able to use the vision lib rather than `POST`ing directly to the `images:annotate` endpoint.

I've tried stringifying the Credentials object, then parsing and passing it into the constructor, but then I get strange errors like `Auth error:Error: invalid_grant: Invalid JWT Signature.` Plus that just seems like more hoops to jump through than necessary, considering the Vision API supports API keys.

```js
// Throws like 10 invalid_grant errors

const visionClient = new vision.ImageAnnotatorClient({
    credentials: JSON.parse(GOOGLE_APPLICATION_CREDENTIALS),
});

visionClient.cropHints(buffer)
    .then(results => console.log(results));
```

**Comment by stephenplusplus** [comment]
*Tagging related issue: https://github.com/googleapis/nodejs-speech/issues/19*

I agree, it would be great to support this. Our first hurdle will be to figure out what to do with an API key once the user gives one to us. There are a couple of layers beneath us:

- GAPIC: This is an auto-generated codebase that makes raw requests through gRPC. We need to figure out if it accepts an API key.
- gRPC: If the GAPIC layer doesn't accept API keys, we might need to figure out how to do it ourselves with gRPC.

cc @alexander-fenster @crwilcox in case you have the answer already or any general opinions on if and how we would accept API keys.

**Comment by Mr-SD** [comment]
Any updates on this?

**Comment by cor1** [comment]
any update on this? been almost a year :/

**Comment by bcoe** [comment]
@cor1 we're currently in the process of discussing/designing authentication improvements across the board on our client libraries; we're hoping to have a better story about how to support tokens, etc.

No immediate updates, but promise this is something we're working on :+1:

**Comment by remzr7** [comment]
Any updates on this?

**Comment by chougron** [comment]
Would it be as easy as passing the key parameter in each call like described in the documentation, or am I missing something ? https://cloud.google.com/docs/authentication/api-keys#using_an_api_key
It would be much appreciated to be able to do that, as we can not easily put the file in a server we programmatically create, and leaving a json service file easily readable in our repository is not so good...

**Comment by alexander-fenster** [comment]
@chougron Oh, this issue seems to be forgotten here, sorry for that! Using an API key from the Node.js application is a little bit tricky but totally possible. This [gist](https://gist.github.com/alexander-fenster/9607dafe499c9059123fe41abe41c6b7) shows the complete example, here is the main part of it:

```js
const apiKey = 'REDACTED'; // <-- use your API key here
const vision = require('@google-cloud/vision');
const {GoogleAuth, grpc} = require('google-gax');

function getApiKeyCredentials() {
  const sslCreds = grpc.credentials.createSsl();
  const googleAuth = new GoogleAuth();
  const authClient = googleAuth.fromAPIKey(apiKey);
  const credentials = grpc.credentials.combineChannelCredentials(
    sslCreds,
    grpc.credentials.createFromGoogleCredential(authClient)
  );
  return credentials;
}
...
// initialize the client
const sslCreds = getApiKeyCredentials();
const client = new vision.ImageAnnotatorClient({sslCreds});
```

Let me know if this helps!

**Comment by alexander-fenster** [comment]
@chougron As for just passing the key as a parameter, this client library uses gRPC and not an HTTP so there technically is no URI to append the parameter to.

**Comment by asraful** [comment]
@alexander-fenster   your solution works without any issue .

**Comment by asraful** [comment]
@alexander-fenster  your solution workes for me as well.
