### ISSUE TITLE
samples tests failure

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-vision#64]
Several samples tests failed in today's nightly testing for Vision Node.js client library:

https://circleci.com/gh/googleapis/nodejs-vision/2102

 ✖ detect.v1p1beta1 › should detect web entities using geographical metadata
 ✖ detect › should detect web entities with geo metadata in remote file 
 ✖ detect › should detect web entities with geo metadata in local file 

Looks like something has changed with the geo data so the server returned different answers than the test expected. We want to take nightly test failures seriously as they can mask real problems, so can I ask you to take a look at the failures and fix them if possible.

Thanks!

**Comment by alexander-fenster** [comment]
@happyhuman, @beccca - could you please take a look? It breaks our nightly testing.
Thanks!

**Comment by happyhuman** [comment]
I am not familiar with these samples, but sure, I will take a look.

**Comment by alexander-fenster** [comment]
FYI, there is an open PR from @beccca #53 that might remove one of the failing tests. Not sure if it should be merged or not, and when. For the others, it looks like the API sometimes returns different answers (the tests sometimes pass, but sometimes fail). Since we test Node.js samples, and not the API consistency, we might need to make some fixes to the tests to ignore these changes in API responses.

**Comment by alexander-fenster** [comment]
cc @crwilcox, @JustinBeckwith

**Comment by happyhuman** [comment]
I believe this is fixed now.

**Comment by alexander-fenster** [comment]
Thanks @happyhuman , two of three tests are fixed. This one still fails:

  ✖ detect.v1p1beta1 › should detect web entities using geographical metadata

I'm not sure if #53 is going to land any time soon, so should we just remove this test or fix it as well?

Thanks!

**Comment by happyhuman** [comment]
How strange. It worked the other day and passed all the tests. Okay, I will look at it now.   :)

**Comment by alexander-fenster** [comment]
It passes now. This is not a _unit_ test after all, so it's expected that it might fail whenever the API changes something on their side. I verified everything passes right now, so let's give it a try and see how it works. If it starts failing again in a week or so, we'll need to think of some other way of testing these samples.

Thanks for taking a look!
