### ISSUE TITLE
IAM permission for service account

### ISSUE THREAD

**Issue by Mistic92** [googleapis/nodejs-vision#789]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
We have for example 3 project with vision buckets and one project with cloud run(let's call this CR project). We wanted to create service account in CR project, add to 3 vision projects and use buckets from it. Unfortunately it's not working. Is this a bug or weird design? The same thing is working with Dialogflow. 

What permissions should service account have to use vision api?

**Comment by munkhuushmgl** [comment]
@Mistic92 I need a bit more information from your-end.

1. What you do mean by vision bucket? GCS Bucket contains images or please specify.
2. Could you describe a bit more about 3 projects with vision. buckets? (three project each it has its own bucket?)
3. Are you trying to access cross-project bucket?
4. Could you share an error log?

**Comment by Mistic92** [comment]
Hi, sorry. 
1. By bucket I mean Product Set from GCP Vision Product Search. 
2. So we are creating 3 projects (one per client) to use product search on their images. We have 1 central project for backend (cloud run/gke) and we need to call product search from this project to one of 3 with product sets. 
3. Kind of yes
4. I'll need to ask team for exact log but from what I remember it was permission denied.

**Comment by munkhuushmgl** [comment]
@Mistic92 Could you tell me a bit about how you guys set up your cross-project access?
For example, let's call backend project A and other 3 B, C, D?
1. On which project, did you guys create a service account ?
 2. What kind of access SA have ?

**Comment by Mistic92** [comment]
Sure, so 
A - cloudrun, business logic etc
B, C, D - only vision with product sets

1. We wanted to create SA on A and add it on IAM for B,C,D. 
2. We were trying to use even owner but no change. 

We have ended creating SA on B,C,D, downloading keys, adding manually to A and using them for creating singletons for each project. It's super bad design as we don't have key rotation and will have trouble when we'll have larger number of vision projects. 

For example we could use key from A in B,C,D when using Dialogflow API.

**Comment by munkhuushmgl** [comment]
@Mistic92 Okay if that's case, I will reach out Vision product team to see if they support cross-project access.

**Comment by Mistic92** [comment]
@munkhuushmgl thanks, we jump on vc if needed to talk about other details. Maybe office hours or something like that :)

**Comment by munkhuushmgl** [comment]
@Mistic92 Did you get this kind of error?
```
  error {
    code: 7
    message: "Error opening file: gs://some-bucket/product-search_shoes_1.jpg."
  }

```

**Comment by Mistic92** [comment]
I have more info from team. We are getting response 200 but all fields are empty and message field have PERMISSION_DENIED error
```json
[
    {
        "responses": [
            {
                "faceAnnotations": [],
                "landmarkAnnotations": [],
                "logoAnnotations": [],
                "labelAnnotations": [],
                "textAnnotations": [],
                "localizedObjectAnnotations": [],
                "safeSearchAnnotation": null,
                "imagePropertiesAnnotation": null,
                "error": {
                    "details": [],
                    "code": 7,
                    "message": "Permission denied."
                },
                "cropHintsAnnotation": null,
                "fullTextAnnotation": null,
                "webDetection": null,
                "productSearchResults": null,
                "context": null
            }
        ]
    },
    null,
    null
]

```

I also have code snippets
```ts
import * as googleApi from "@google-cloud/vision"
this._visionClient = new googleApi.v1.ImageAnnotatorClient()

const request = {
image: { content: imageData.toString("base64") },
};

let results = await this._visionClient.objectLocalization(request);
```
```ts
/** @format */

import * as googleApi from "@google-cloud/vision";
this._visionClient = new googleApi.v1.ImageAnnotatorClient();

const request = {
  image: { content: img.toString("base64") },
  features: [{ type: "PRODUCT_SEARCH", maxResults: settings.maxItems }],
  imageContext: {
    productSearchParams: {
      productSet: `projects/${settings.projectId}/locations/${settings.locationId}/productSets/${settings.productSetId}`,
      productCategories: settings.productCategories,
    },
  },
};

const response = await this._visionClient.batchAnnotateImages({
  requests: [request],
});

```

**Comment by brendanlundy** [comment]
Unfortunately, it's not possible to make an annotation request to a ProductSet in a different project.

You have 2 options:

A) If you have to keep the ProductSets in 3 different projects, then you will have to use 3 different service accounts for annotation.

B) Put all of the ProductSets into a single project and make sure the ProductSet ids and Product ids from different customers don't collide. Then you just need 1 service account. When you do the batch import, the images can be in any project's GCS bucket, as long as you have read access to those images.

**Comment by Mistic92** [comment]
Can we make it as feature request for internal team?
