### ISSUE TITLE
Using Rest V1p4beta1

### ISSUE THREAD

**Issue by iamsabet** [googleapis/nodejs-vision#817]
hi. I had a question
i wondered how to use https://vision.googleapis.com/(v1p4beta1)/files:asyncBatchAnnotate
using this. package in node
my current version is the latest "@google-cloud/vision": "^2.1.1",
running like this 

<img width="1203" alt="Screen Shot 2020-08-16 at 4 34 55 PM" src="https://user-images.githubusercontent.com/20267993/90333856-75c80d00-dfde-11ea-815d-d7415c90145e.png">

 I appreciate a response

the original problem is that in some documents I am missing blocks with Bloc.blockType of = "PICTURE", "TABLE" 
, ...
I only get those blockType=="TEXT"

wanted to use beta. the latest version to see if there's an improvement in coverage for my case

@bcoe

**Comment by iamsabet** [comment]
@bcoe

**Comment by bcoe** [comment]
@iamsabet you should be able to do this:

```js
async main () {
  const { ImageAnnotatorClient } = require('@google-cloud/vision').v1p4beta1
  const client = new ImageAnnotatorClient()
  await client.asyncBatchAnnotate(...)
}
main()
```

Let me know if this  does the trick for you?

**Comment by iamsabet** [comment]
ty so much, it resolved.
