### ISSUE TITLE
TypeError: client.elevation is not a function

### ISSUE THREAD

**Issue by SuperfectusTv** [googleapis/nodejs-vision#859]
Hi,

When i used to run this code its work but i think with a new update this code is no longer working.

My Code is: 

```
const ayarlar = require('../ayarlar.json');
module.exports = message => {
  let client = message.client;
  if (message.author.bot) return;
  if (!message.content.startsWith(ayarlar.prefix)) return;
  let command = message.content.split(' ')[0].slice(ayarlar.prefix.length);
  let params = message.content.split(' ').slice(1);
  let perms = client.elevation(message);
  let cmd;
  if (client.commands.has(command)) {
    cmd = client.commands.get(command);
  } else if (client.aliases.has(command)) {
    cmd = client.commands.get(client.aliases.get(command));
  }
  if (cmd) {
    if (perms < cmd.conf.permLevel) return;
    cmd.run(client, message, params, perms);
  }

};
```

Thanks For Help...

**Comment by munkhuushmgl** [comment]
I cannot reproduce this code without more context from you.
What is 
`const ayarlar = require('../ayarlar.json');`?

I cannot run cannot your code without knowing what is message object or message client?


Last question: How's related to nodejs-vision library?

**Comment by SuperfectusTv** [comment]
its my Setting.json Like

{
  "prefix":"!",
  "token":"MyTokenHere",
  "owner":"MyDiscord_id"
}

**Comment by munkhuushmgl** [comment]
What is message object?
I need a clear picture how your dependencies and code structured?

which version of API are you using?

**Comment by munkhuushmgl** [comment]
Due to inactivity, I am closing this issue. Feel free to reopen this issue.
