### ISSUE TITLE
feat request: support pages on asyncBatchAnnotateFiles request.

### ISSUE THREAD

**Issue by nthypes** [googleapis/nodejs-vision#883]
It's not possible to specify **pages** in a request of `asyncBatchAnnotateFiles` ?

If not, can we ship this as a feature?

**Comment by meredithslota** [comment]
I'm not totally clear on what this request means — https://cloud.google.com/vision/docs/reference/rpc/google.cloud.vision.v1#google.cloud.vision.v1.BatchAnnotateImagesRequest allows multiple image annotation requests batched into a single call. If you are still interested in this feature, please file a new issue in the consolidated library repo, at https://github.com/googleapis/google-cloud-node/issues, as this repo is moving there shortly. Thanks!
