### ISSUE TITLE
feat request: support textDetectionParams on asyncBatchAnnotateFiles request.

### ISSUE THREAD

**Issue by nthypes** [googleapis/nodejs-vision#884]
It's not possible to specify **textDetectionParams** in a request of asyncBatchAnnotateFiles ?

If not, can we ship this as a feature?

**Comment by meredithslota** [comment]
I'm not totally clear on what this request means — https://cloud.google.com/vision/docs/fulltext-annotations gives an overview for how to do this (although the tutorial references the Python library, the approach is similar) If you are still interested in this feature, please file a new issue in the consolidated library repo, at https://github.com/googleapis/google-cloud-node/issues, as this repo is moving there shortly. Thanks!
