### ISSUE TITLE
Using Buffer doesn't work 

### ISSUE THREAD

**Issue by Khalid-Nowaf** [googleapis/nodejs-vision#9]
#### Environment details

  - OS: OSX
  - Node.js version: v6.11.4
  - npm version: 3.10.10
  - @google-cloud/vision version:  ^0.13.0

#### Steps to reproduce

I have a firebase function, that accepts base64 string, then convert it to buffer. 
Everything runs with no problem, but the response from Vision API is always an empty array. I pass the same image with the file path, I got a correct response. 

here my is an example 

````js
// req.base64data is a string from the client using FileReader API 
client
  .faceDetection( new Buffer(req.base64data,'base64'))
  .then(results => {
    const faces = results[0].faceAnnotations;
        console.log("RESULT:", faces.length);
        return res.send({data:faces.length});
  })
  .catch(err => {
    console.error('ERROR:', err);
  });
```

Thanks!

**Comment by lukesneeringer** [comment]
Confirmed that I would expect this to work. In Node 6.12...

```es6
> let b = Buffer.from('this is some data')
undefined
> b
<Buffer 74 68 69 73 20 69 73 20 73 6f 6d 65 20 64 61 74 61>
> b.toString()
'this is some data'
> let b64 = b.toString('base64')
undefined
> b64
'dGhpcyBpcyBzb21lIGRhdGE='
> let b2 = new Buffer(b64, 'base64')
undefined
> b2
<Buffer 74 68 69 73 20 69 73 20 73 6f 6d 65 20 64 61 74 61>
```

**Comment by Khalid-Nowaf** [comment]
I use Firebase cloud functions, so I don't really know that is the nodejs runtime there. but I try many ways to create a buffer from a base64 string. but for me, it does not make sense to convert the base64 to buffer then the nodejs-vision convert to back to a base64 string? 

but I would suggest adding new option which is a base64 string instead of buffer. so the developer has the option to pass one of the following  (filename, buffer, base64 string).

**Comment by lukesneeringer** [comment]
The Vision API actually accepts base64 strings outright (we convert _into_ base64 strings if you pass a buffer). Just send:

```es6
{image: {source: {content: 'base64 string'}}}
```

**Comment by Khalid-Nowaf** [comment]
I did not know that ^^!!, spent most of my weekend to find a way to create the buffer that would works^^

**Comment by lukesneeringer** [comment]
Did that fix your issue?

**Comment by Khalid-Nowaf** [comment]
yes
