### ISSUE TITLE
How do I add callOptions to `faceDetection ()`?

### ISSUE THREAD

**Issue by huequica** [googleapis/nodejs-vision#902]
I'm trying to set a detection limit for `ImageAnnotatorClient.faceDetection()`.  
However, when I try to put the Object of CallOptions described in the [document](https://googleapis.dev/nodejs/vision/latest/v1.ImageAnnotatorClient.html#faceDetection), an error is returned.  

```.ts
const visionAPI = new vision.ImageAnnotatorClient({
	projectId: GCPProjectID,
	keyFilename: '.envs/serviceAccount.json'
});
const [faceDetectionResult] = await visionAPI.faceDetection(DetectionImageFilePath, {maxResults: 10});
```
![スクリーンショット 2021-05-13 033639](https://user-images.githubusercontent.com/40014236/118027405-d97c3c80-b39c-11eb-8232-818841700cc2.png)

----------

The depends version I'm using are listed below.

```package.json
"dependencies": {
    "@google-cloud/vision": "^2.3.1",
	"typescript": "^4.2.4",
```

```bash
$ node -v
v14.16.1
```

**Comment by munkhuushmgl** [comment]
```
const options = {maxResults: 10};
const [faceDetectionResult] = await visionAPI.faceDetection(DetectionImageFilePath, options);
```

**Comment by munkhuushmgl** [comment]
With the snippet provided above, I am closing this issue.

If you still experiencing any issue, feel free to reopen

Thanks
