### ISSUE TITLE
Socket hang up

### ISSUE THREAD

**Issue by MallRoy** [googleapis/nodejs-vision#903]
When I continuously call the vision API, it throws a socket hang-up error. 
![image](https://user-images.githubusercontent.com/54269166/118609527-747b7900-b7d8-11eb-982e-284d436cf4a3.png)

![image](https://user-images.githubusercontent.com/54269166/118609211-26667580-b7d8-11eb-8822-993ccc10d864.png)

I am using the Node 14 version. I am using the below code to detect the text for a PDF document.
```
  const client = new vision.ImageAnnotatorClient({
      credentials: {
        client_email: '',
        private_key: '',
      }})      
  const features = [{ type: 'DOCUMENT_TEXT_DETECTION' }];
      const request = {
        requests: [
          {
            inputConfig: inputConfig,
            features: features,
            outputConfig: outputConfig,
          },
        ],
      };
      const [operation] = await client.asyncBatchAnnotateFiles(request);
      const [filesResponse] = await operation.promise();
```

**Comment by kweinmeister** [comment]
Thank you for filing this issue. We asked some clarifying questions and haven't heard back yet. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
