### ISSUE TITLE
ImageAnnotatorClient ignores the projectId option and environment variables

### ISSUE THREAD

**Issue by edonosotti** [googleapis/nodejs-vision#933]
I can't get `ImageAnnotatorClient` to use a specific project.

This code:

```javascript
const vision = require("@google-cloud/vision");

const visionClient = new vision.v1.ImageAnnotatorClient({
  projectId: "REDACTED_PROJECT_ID",
});

async function detect() {
  const [result] = await visionClient.objectLocalization("REDACTED_PATH");
}

detect();
```

Started with:

```bash
$ GCP_PROJECT=REDACTED_PROJECT_ID \
  GCLOUD_PROJECT=REDACTED_PROJECT_ID \
  node test_script.js
```

returns error:

```
code: 7,
details: 'Cloud Vision API has not been used in project 
REDACTED_DEFAULT_PROJECT_NUMBER_OF_DEFAULT_CONFIG 
before or it is disabled. Enable it by visiting ...',
```

Apparently, the class is **completely ignoring** both the `REDACTED_PROJECT_ID`, set in several different places, and the **default project ID of the active gcloud configuration**. Instead, it picks up the _default_ project ID of the _default_ configuration (**which is not even active**).

#### Environment details

  - Node.js version: v15.8.0
  - npm version: 7.5.1
  - `@google-cloud/vision` version: 2.3.7

**Comment by kweinmeister** [comment]
Hi, as we haven't heard back for a while, I'll go ahead and close this issue. Please feel free to reopen if it is still a problem.
