### ISSUE TITLE
Incomplete ImprovedRequest TypeScript interface

### ISSUE THREAD

**Issue by clorichel** [googleapis/nodejs-vision#963]
#### Environment details

  - OS: _irrelevant_
  - Node.js version: _irrelevant_
  - npm version: _irrelevant_
  - `@google-cloud/vision` version: 2.4.0

#### Steps to reproduce

```typescript
const client = new vision.ImageAnnotatorClient();
const [result] = await client.cropHints({ image: { source: { filename } }, imageContext: {} });
```

Gives you an `'imageContext' does not exist in type 'ImprovedRequest | Buffer'` TypeScript error.

#### Description

That might not be an issue only for the `cropHints` feature, but any ImageAnnotatorClient feature which method signature is equivalent/limited to `(request: string | ImprovedRequest | Buffer)`.

The appropriate JSON representation is documented here: https://cloud.google.com/vision/docs/reference/rest/v1/AnnotateImageRequest where we can see that `imageContext` is possible, yet not in this package `ImprovedRequest` interface. Then one could drill it down to https://cloud.google.com/vision/docs/reference/rest/v1/ImageContext to actually provide a thorough interface.

#### Workaround

The request actually works fine if you simply cast the method parameter through `client.cropHints({ image: { source: { filename } }, imageContext: {} } as any)`: the imageContext is passed down to the underlying service and used as one could expect to generate the response.

**Comment by Tobjoern** [comment]
I'm facing this issue right now.

**Comment by summer-ji-eng** [comment]
Will take deep look in Jan and keep post here.

**Comment by summer-ji-eng** [comment]
@galz10 @bcoe could you help to take a look at here? `ImprovedRequest` is from [helper.ts](https://github.com/googleapis/nodejs-vision/blob/main/src/helpers.ts#L44), which is not generated from gapic-generator-typescript. I wonder if it is a manual layer.
