### ISSUE TITLE
Missing `types` in `package.json`

### ISSUE THREAD

**Issue by marcushultman** [googleapis/nodejs-vision#971]
#### Environment details

  - OS: N/A
  - Node.js version: N/A
  - npm version: N/A
  - `@google-cloud/vision` version: 2.4.1

#### Steps to reproduce

  1. Inspect package.json

#### Description

The package contains `build/src/index.d.ts` next to the `main` entrypoint (`build/src/index.js`). While some TypeScript environments can interpret this correctly without a `types`/`typings`-field in the `package.json, the [TypeScript Handbook says it's "advisable to do so"](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package).

**Comment by galz10** [comment]
@marcushultman i'm not seeing `index.d.ts` in our repo, can you point me to this file .

**Comment by marcushultman** [comment]
@galz10 It should be generated in the `build/` directory after `compile`.

**Comment by galz10** [comment]
Fixing #977
