### ISSUE TITLE
Any plan to enhance API documentation?

### ISSUE THREAD

**Issue by bvamos** [googleapis/nodejs-vision#998]
Hi, can I find precise API documentation? Here is an [example](https://googleapis.dev/nodejs/vision/latest/google.cloud.vision.v1.EntityAnnotation.html) from the current one:

    EntityAnnotation Members
      boundingPoly
      EntityAnnotation boundingPoly.

It is very hard to figure out what are the methods and properties for.

**Comment by kweinmeister** [comment]
Hi, please check out the [latest version](https://cloud.google.com/java/docs/reference/google-cloud-vision/latest/overview) of the documentation on cloud.google.com. [Here](https://cloud.google.com/java/docs/reference/google-cloud-vision/latest/com.google.cloud.vision.v1.EntityAnnotation#com_google_cloud_vision_v1_EntityAnnotation_getBoundingPoly__) is the getBoundingPoly() method, which provides more detail.

BTW, we've replaced the link on this repo's README to point to the updated documentation. Is there another link pointing to the older documentation we need to replace?
