### ISSUE TITLE
How to stream image / not read into memory?

### ISSUE THREAD

**Issue by jstayton** [googleapis/nodejs-vision#999]
Hey 👋🏻

I'm currently annotating an image with the following code:

```js
const imageBuffer = ...

const client = new vision.ImageAnnotatorClient({ ... })

const [results] = await client.annotateImage({
  image: {
    content: imageBuffer,
  },
  features: [...],
})
```

After scouring through the documentation, I'm not seeing any way to use a stream instead of a buffer, so that the whole image isn't ready into memory. Am I just missing it? Or is it not possible?

Thanks!

**Comment by kweinmeister** [comment]
Here's an [example](https://github.com/googleapis/nodejs-vision/blob/main/samples/async-batch-annotate-images.js) of specifying a source URI rather than a content buffer. Does that help?

**Comment by jstayton** [comment]
Hmmm. I guess I could use a stream to upload to Google Cloud Storage ([like this example](https://github.com/googleapis/nodejs-storage/blob/main/samples/streamFileUpload.js)), and then specify the `gs` URL like in the example above?

**Comment by kweinmeister** [comment]
Yes, that would be the best approach, as we currently don't support streaming in this library.
